const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {submit}=require('./submit-task-plan');
function fixture(extra={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'submit-plan-'));fs.writeFileSync(path.join(dir,'draft.json'),JSON.stringify({id:'draft',kind:'task',name:'Validate configuration',tasks:[],...extra}));return dir;}
test('submission retains the exact reviewed plan and server identity with Planner approval',async()=>{
 const dir=fixture();let saved,payload;const url='https://github.com/example/tasks/issues/62';
 const result=await submit({id:'draft',markdown:'## Plan\nValidate before saving.'},{dir,login:async()=> 'reviewer',server:()=>({type:'github'}),sync:async p=>{payload=p;return {ok:true,key:'#62',url};},core:{planHash:()=> 'hash',save:(u,s)=>saved={u,...s}}});
 assert.equal(payload.task.issueType,'task');assert.equal(saved.plan,payload.task.body);assert.equal(saved.plannerProjectId,'draft');assert.equal(saved.planApproval.source,'task-planner');assert.equal(saved.planApproval.githubLogin,'reviewer');assert.equal(saved.phase,'plan-approved');assert.equal(result.project.workTaskUrl,url);
});
test('required signoff is checked before creating or updating a server issue',async()=>{const dir=fixture({requiredSignoff:{name:'Tim',githubLogin:'tim',scope:'both'}});await assert.rejects(submit({id:'draft',markdown:'Plan'},{dir,login:async()=> 'other',sync:()=>assert.fail('must not submit')}),/Tim/);});
test('sync failure does not mark a plan approved',async()=>{const dir=fixture();await assert.rejects(submit({id:'draft',markdown:'Plan'},{dir,login:async()=> 'reviewer',server:()=>({type:'github'}),sync:async()=>({ok:false,error:'Server unavailable'}),core:{save:()=>assert.fail('must not approve')}}),/Server unavailable/);assert.equal(JSON.parse(fs.readFileSync(path.join(dir,'draft.json'))).workTaskUrl,undefined);});
