'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {GraphWorkspace}=require('./graph-workspace'),svc=require('./app-configuration-import');
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'robos-app-import-')),file=path.join(dir,'settings.json'),workspace=new GraphWorkspace(path.join(dir,'graph'));
const evidence=[{repository:'example',path:'config.json',line:1,revision:'test',sha256:'a'.repeat(64)}];
const nodes=[{'@id':'urn:example:server:issues','@type':['robos:TaskServer'],'dcterms:title':'Issues','robos:package':'organization','robos:serverType':'github','robos:url':'https://github.com/example/issues','robos:projectKey':'example/issues','robos:evidence':evidence},{'@id':'urn:example:server:ci','@type':['robos:CIPipelineServer'],'dcterms:title':'CI','robos:package':'devops','robos:provider':'jenkins','robos:url':'https://ci.example.test','robos:credentialRef':'pass:ci','robos:evidence':evidence}];
const p=workspace.propose({mode:'refine',edits:nodes.map(node=>({op:'add',node})),requireEvidence:true});workspace.apply(p);
fs.writeFileSync(file,JSON.stringify({unrelated:true,task_servers:[{id:'existing',name:'My issues',type:'github',repos:[{org:'example',repo:'issues'}],use_gh_cli:false,gh_token_pass_path:'existing-token'}]}));return {dir,file,workspace};}
test('imports server metadata and workflows, preserves credentials, and is repeatable',()=>{
 const {file,workspace}=fixture(),input=svc.scan(workspace.root,file);input.taskServers[0].issue_types=[{id:'task',label:'Task'}];input.taskServers[0].workflows=[{id:'task-flow',name:'Task',type_id:'task',states:[{id:'open',is_initial:true},{id:'done'}],transitions:[{from:'open',to:'done'}]}];
 const preview=svc.plan(input,file);assert.equal(JSON.parse(fs.readFileSync(file)).task_servers[0].issue_types,undefined);svc.apply(preview,file);
 const saved=JSON.parse(fs.readFileSync(file));assert.equal(saved.unrelated,true);assert.equal(saved.task_servers.length,1);assert.equal(saved.task_servers[0].id,'existing');assert.equal(saved.task_servers[0].gh_token_pass_path,'existing-token');assert.equal(saved.task_servers[0].workflows.length,1);assert.equal(saved.ci_pipeline_servers[0].credentialRef,'pass:ci');
 const again=svc.plan(svc.scan(workspace.root,file),file);assert.equal(again.proposal,null);svc.apply(again,file);assert.equal(JSON.parse(fs.readFileSync(file)).task_servers.length,1);
});
test('rejects stale settings and invalid transitions before applying',()=>{const {file,workspace}=fixture(),input=svc.scan(workspace.root,file);input.taskServers[0].issue_types=[{id:'task',label:'Task'}];input.taskServers[0].workflows=[{type_id:'task',states:[{id:'open',is_initial:true}],transitions:[{from:'open',to:'unknown'}]}];assert.throws(()=>svc.plan(input,file),/unknown state/);input.taskServers[0].workflows=[];const preview=svc.plan(input,file);fs.writeFileSync(file,'{}');assert.throws(()=>svc.apply(preview,file),/changed/);});
test('discovers native types as well as labels without inventing transitions',async()=>{const result=await svc.discover({type:'github',repos:[{org:'example',repo:'issues'}]},async args=>args[1].startsWith('orgs/')?[{id:1,name:'Task',description:'Work'}]:[[{name:'type:feature',color:'123456'}]]);assert.deepEqual(result.issueTypes.map(t=>t.id),['task','feature']);assert.equal(result.workflows,undefined);});
