'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {promisify}=require('node:util'),exec=promisify(require('node:child_process').execFile);
const digest=s=>crypto.createHash('sha256').update(s).digest('hex');
const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
function normalizeDomains(value=[]){
 const entries=Array.isArray(value)?value:String(value).split(/[\s,;]+/);
 return [...new Set(entries.map(v=>String(v).trim().toLowerCase().replace(/^@/,'')).filter(Boolean).map(domain=>{
  if(domain.length>253||!domain.includes('.')||!domain.split('.').every(label=>/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/.test(label)))throw Error('Enter email domains such as @example.com, separated by commas or new lines.');
  return domain;
 }))];
}
async function discover({repositories=[],gcloudProjects=[],emailDomains=[]},run=async(cmd,args)=>(await exec(cmd,args,{maxBuffer:32*1024*1024,timeout:60000})).stdout){
 const domains=normalizeDomains(emailDomains),excluded=new Set();
 const people=new Map(),groups=[],warnings=[],seen=new Set();
 function add(name,email,source){email=email.toLowerCase();if(!email||/\[bot\]|noreply.*bot|serviceaccount/i.test(name+' '+email))return;if(domains.length&&!domains.includes(email.slice(email.lastIndexOf('@')+1))){excluded.add(email);return;}let p=people.get(email);if(!p){p={uid:'person-'+digest(email).slice(0,16),displayName:name||email,email,aliases:[],sources:[],selected:false};people.set(email,p);}if(!p.aliases.includes(name))p.aliases.push(name);if(!p.sources.some(s=>s.repository===source.repository))p.sources.push(source);}
 for(const repo of repositories){try{const origin=(await run('git',['-C',repo,'remote','get-url','origin'])).trim().replace(/\.git$/,'').replace(/^git@github.com:/,'https://github.com/');if(seen.has(origin))continue;seen.add(origin);const log=await run('git',['-C',repo,'log','--all','--format=%H%x09%aN%x09%aE']);for(const line of log.trim().split('\n')){const [revision,name,email]=line.split('\t');if(email)add(name,email,{repository:origin,path:'git-history',revision,sha256:digest(line),line:1});}}catch(e){warnings.push(`${repo}: ${e.message}`);}}
 for(const project of gcloudProjects){if(!/^[a-z][a-z0-9-]{4,62}$/.test(project))throw Error('Invalid Google Cloud project ID');try{const raw=await run('gcloud',['projects','get-iam-policy',project,'--format=json']),policy=JSON.parse(raw),source={repository:'https://cloud.google.com/resource-manager',path:`projects/${project}/iam-policy`,revision:new Date().toISOString(),sha256:digest(raw),line:1};for(const binding of policy.bindings||[])for(const member of binding.members||[]){if(member.startsWith('user:'))add(member.slice(5),member.slice(5),source);if(member.startsWith('group:')&&!groups.some(g=>g.email===member.slice(6)))groups.push({email:member.slice(6),sources:[source],members:[]});}}catch(e){warnings.push(`${project}: ${e.message}`);}}
 return {emailDomains:domains,excludedPeople:excluded.size,people:[...people.values()].sort((a,b)=>a.displayName.localeCompare(b.displayName)),groups,warnings};
}
function confirmedPerson({name,email,emailDomains=[]}){
 name=String(name||'').trim();email=String(email||'').trim().toLowerCase();
 if(!name||name.length>200||! /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter a name and valid email address.');
 const domains=normalizeDomains(emailDomains);if(domains.length&&!domains.includes(email.split('@')[1]))throw Error('This email is outside the selected domain filter.');
 const assertion=JSON.stringify({name,email});
 return {uid:'person-'+digest(email).slice(0,16),displayName:name,email,aliases:[name],selected:true,sources:[{repository:'robos-import:user-confirmed',path:'confirmed-person',revision:new Date().toISOString(),line:1,sha256:digest(assertion),assertion}]};
}
function parseGroups(prompt,people){const selected=people.filter(p=>p.selected);const groups=[];for(const line of prompt.split('\n').map(s=>s.trim()).filter(Boolean)){const i=line.indexOf(':');if(i<1)throw Error('Use one group per line: Group name: person email, person email');const name=line.slice(0,i).trim(),members=line.slice(i+1).split(',').map(s=>s.trim()).filter(Boolean).map(token=>{const matches=selected.filter(p=>[p.email,p.displayName,...p.aliases||[]].some(v=>v.toLowerCase()===token.toLowerCase()));if(matches.length!==1)throw Error(`Choose one imported user for “${token}”; use their email to disambiguate.`);return matches[0].uid;});if(groups.some(g=>g.id===slug(name)))throw Error('Duplicate group name');groups.push({id:slug(name),name,members:[...new Set(members)],description:'Membership supplied in the reviewed import prompt.'});}return groups;}
function existing(dir){if(!fs.existsSync(dir))return [];return fs.readdirSync(dir).filter(f=>f.endsWith('.json')&&f!=='config.json').map(f=>JSON.parse(fs.readFileSync(path.join(dir,f),'utf8')));}
function prepare(input,nodes,base){const domains=normalizeDomains(input.emailDomains||[]);const people=(input.people||[]).filter(p=>p.selected),groups=parseGroups(input.groupPrompt||'',input.people||[]),edits=[],writes=[];
 const oldPeople=existing(path.join(base,'people')),oldGroups=existing(path.join(base,'groups')),ids=new Map();
 const put=(node)=>{const old=nodes.find(n=>n['@id']===node['@id']);if(!old)edits.push({op:'add',node});else {const {'@id':id,...set}=node;edits.push({op:'update',id,set});}};
 for(const person of people){if(domains.length&&!domains.includes(String(person.email).toLowerCase().split('@').pop()))throw Error('Selected person falls outside the email-domain filter. Discover users again.');if(!person.displayName?.trim()||!person.email?.includes('@')||!person.sources?.length)throw Error('Every imported person needs a name, email, and source evidence.');const matches=oldPeople.filter(p=>p.email?.toLowerCase()===person.email.toLowerCase());if(matches.length>1)throw Error('Resolve duplicate People Directory emails before importing.');const old=matches[0],uid=old?.uid||person.uid;if(!/^[a-zA-Z0-9_-]+$/.test(uid))throw Error('Invalid person ID');ids.set(person.uid,uid);const graphOld=nodes.find(n=>n['robos:email']===person.email&&[].concat(n['@type']).includes('oslc:Person'));const graphId=graphOld?.['@id']||'urn:robos:person:'+uid;person.graphId=graphId;const row={...old,uid,displayName:person.displayName,email:person.email,aliases:person.aliases,sources:person.sources,kgraphId:graphId};writes.push({file:path.join(base,'people',uid+'.json'),data:row});put({'@id':graphId,'@type':['oslc:Person'],'dcterms:title':person.displayName,'robos:package':'organization','robos:email':person.email,'robos:evidence':person.sources});}
 for(const group of groups){if(!group.id)throw Error('Group name needs letters or numbers');const old=oldGroups.find(g=>g.name?.toLowerCase()===group.name.toLowerCase()),id=old?.id||group.id;if(!/^[a-zA-Z0-9_-]+$/.test(id))throw Error('Invalid group ID');const graphId=old?.kgraphId||'urn:robos:team:'+id;const members=group.members.map(uid=>ids.get(uid));writes.push({file:path.join(base,'groups',id+'.json'),data:{...old,...group,id,members,kgraphId:graphId}});const evidence=[{repository:'robos-import:user-reviewed',path:'group-prompt',revision:digest(input.groupPrompt),sha256:digest(input.groupPrompt),line:1}];put({'@id':graphId,'@type':['robos:Team'],'dcterms:title':group.name,'robos:package':'organization','dcterms:description':group.description,'robos:hasMember':group.members.map(uid=>people.find(p=>p.uid===uid).graphId),'robos:membershipPrompt':input.groupPrompt,'robos:evidence':evidence});}
 for(const w of writes)w.before=fs.existsSync(w.file)?fs.readFileSync(w.file,'utf8'):null;
 return {edits,writes,summary:{people:people.map(p=>({name:p.displayName,email:p.email})),groups:groups.map(g=>({name:g.name,members:g.members.map(uid=>people.find(p=>p.uid===uid).displayName)}))}};
}
module.exports={confirmedPerson,normalizeDomains,discover,parseGroups,prepare,existing};
