'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sdlcGraph', {
  getAllNodes: () => ipcRenderer.invoke('graph-get-all'),
  query: (filter) => ipcRenderer.invoke('graph-query', filter),
  getNode: (id) => ipcRenderer.invoke('graph-get-node', id),
  findDependents: (id) => ipcRenderer.invoke('graph-find-dependents', id),
  validate: () => ipcRenderer.invoke('graph-validate'),
  listBranches: () => ipcRenderer.invoke('graph-list-branches'),
  getActiveBranch: () => ipcRenderer.invoke('graph-get-active-branch'),
  switchBranch: (branchName) => ipcRenderer.invoke('graph-switch-branch', branchName),
  diffBranches: (base, target) => ipcRenderer.invoke('graph-diff-branches', { base, target }),
  copilotGenerate: (prompt) => ipcRenderer.invoke('graph-copilot-generate', prompt),
  copilotApply: (mutation) => ipcRenderer.invoke('graph-copilot-apply', mutation),
  scanRepo: (dirPath) => ipcRenderer.invoke('graph-repo-scan', dirPath),
  parseGherkin: (text, filePath) => ipcRenderer.invoke('graph-gherkin-parse', { text, filePath }),
  getTraceability: () => ipcRenderer.invoke('graph-gherkin-traceability'),
  generateStepDefs: (scenario) => ipcRenderer.invoke('graph-gherkin-codegen', scenario),
  getFabricHealth: () => ipcRenderer.invoke('graph-fabric-health'),
  resetFabric: () => ipcRenderer.invoke('graph-fabric-reset'),
  dispatchFabric: (method, path, body) => ipcRenderer.invoke('graph-fabric-dispatch', { method, path, body }),
  runEDD: (config) => ipcRenderer.invoke('graph-edd-run', config),
  getEDDStatus: () => ipcRenderer.invoke('graph-edd-status'),
  generateELearning: (prompt) => ipcRenderer.invoke('graph-generate-elearning', prompt),
  generateAppELearning: (options) => ipcRenderer.invoke('graph-app-elearning-generate', options),
  launchAppELearning: (options) => ipcRenderer.invoke('graph-app-elearning-launch', options),
  generateAppDoc: (options) => ipcRenderer.invoke('graph-app-doc-generate', options),
  issueCertificate: (options) => ipcRenderer.invoke('graph-issue-certificate', options),
  getCertificates: (options) => ipcRenderer.invoke('graph-get-certificates', options),
  bulkImportRepos: (repos) => ipcRenderer.invoke('graph-bulk-import-repos', repos),
  importResources: (resources, options) => ipcRenderer.invoke('graph-import-resources', { resources, options }),
  importFromPrompt: (prompt, options) => ipcRenderer.invoke('graph-import-prompt', { prompt, options }),
  importGitProjects: () => ipcRenderer.invoke('graph-import-git-projects'),
  requestAppDocUpdate: (payload) => ipcRenderer.invoke('graph-request-app-doc-update', payload),
  getDocSyncPrompt: () => ipcRenderer.invoke('graph-doc-sync-prompt'),
  applyDocUpdates: (updates) => ipcRenderer.invoke('graph-apply-doc-updates', updates),

  // Multi-Package & Multi-Repo
  listPackages: () => ipcRenderer.invoke('kgraph-list-packages'),
  getPackage: (pkgId) => ipcRenderer.invoke('kgraph-get-package', pkgId),
  listRepos: () => ipcRenderer.invoke('kgraph-list-repos'),
  addRepo: (repoData) => ipcRenderer.invoke('kgraph-add-repo', repoData),
  removeRepo: (repoId) => ipcRenderer.invoke('kgraph-remove-repo', repoId),
  syncRemoteRepo: (repoId) => ipcRenderer.invoke('kgraph-sync-remote', repoId),

  // DevOps Integrations
  getDevOpsCategories: () => ipcRenderer.invoke('devops-get-categories'),
  getDevOpsProviders: (categoryId) => ipcRenderer.invoke('devops-get-providers', categoryId),
  listDevOpsIntegrations: () => ipcRenderer.invoke('devops-list-integrations'),
  saveDevOpsIntegration: (payload) => ipcRenderer.invoke('devops-save-integration', payload),
  testDevOpsConnection: (payload) => ipcRenderer.invoke('devops-test-connection', payload),
  deleteDevOpsIntegration: (id) => ipcRenderer.invoke('devops-delete-integration', id),

  // Advanced KGraph GUI Operations
  addNode: (nodeData) => ipcRenderer.invoke('graph-add-node', nodeData),
  updateNode: (id, patch) => ipcRenderer.invoke('graph-update-node', { id, patch }),
  deleteNode: (id, options = {}) => ipcRenderer.invoke('graph-delete-node', { id, cascade: options.cascade }),
  findPath: (startId, endId, maxDepth) => ipcRenderer.invoke('graph-find-path', { startId, endId, maxDepth }),
  getImpact: (id, depth) => ipcRenderer.invoke('graph-get-impact', { id, depth }),
  generateMermaid: (options) => ipcRenderer.invoke('graph-generate-mermaid', options),
  exportGraph: (format, packageId) => ipcRenderer.invoke('graph-export', { format, packageId }),
  searchNodes: (query, filter) => ipcRenderer.invoke('graph-search-nodes', { query, filter }),
});

