'use strict';
// Shared renderer for plan-derived and legacy RobOS courses. No graph writes here.
class RobOSElearningPlayer extends HTMLElement {
 constructor(){super();this.attachShadow({mode:'open'});this.index=0;this.state={};}
 set course(value){this._course=value;this.index=0;this.state={};try{this.state=JSON.parse(localStorage.getItem(this.storageKey)||'{}');}catch{}this.render();}
 get course(){return this._course;}
 get storageKey(){return 'robos:elearning:'+this._course?.['@id']+':'+JSON.stringify(this._course?.['robos:modules']);}
 get modules(){return this._course?.['robos:modules']||[];}
 complete(i){const m=this.modules[i];return !!this.state['read:'+i]&&(m.labSteps||[]).every((_,j)=>this.state['lab:'+i+':'+j])&&(m.quiz||[]).every((_,j)=>this.state['quiz:'+i+':'+j]===true);}
 get progress(){const done=this.modules.filter((_,i)=>this.complete(i)).length;return {completed:done,total:this.modules.length,percent:Math.round(done/(this.modules.length||1)*100),hasAssessment:this.modules.some(m=>m.quiz?.length),state:structuredClone(this.state)};}
 save(){if(this.hasAttribute('preview')){this.updateProgress();return;}try{localStorage.setItem(this.storageKey,JSON.stringify(this.state));}catch{}this.updateProgress();this.dispatchEvent(new CustomEvent('progress-change',{detail:this.progress,bubbles:true}));}
 text(tag,value,parent){const e=document.createElement(tag);e.textContent=value;parent.append(e);return e;}
 markdown(value,parent){const e=document.createElement('div');if(window.marked&&window.DOMPurify)e.innerHTML=DOMPurify.sanitize(marked.parse(value||''),{USE_PROFILES:{html:true},FORBID_TAGS:['style','form','iframe'],FORBID_ATTR:['style']});else {e.textContent=value||'';e.style.whiteSpace='pre-wrap';}parent.append(e);}
 updateProgress(){const p=this.progress;this.shadowRoot.querySelector('[role=status]').textContent=`${p.completed} of ${p.total} sections completed · ${p.percent}%`;this.shadowRoot.querySelectorAll('[data-module]').forEach(b=>{const i=Number(b.dataset.module);b.textContent=(this.complete(i)?'✓ ':'')+this.modules[i].title;b.setAttribute('aria-current',i===this.index?'step':'false');});}
 editor(){
  const host=this.shadowRoot.querySelector('[data-editor]');if(!window.robosCourseEditor||this.hasAttribute('preview'))return;
  host.innerHTML='<details class="course-editor"><summary>Update course with AI</summary><p>Describe what to improve. Codex will propose an update to this course; your feature plan stays unchanged.</p><robos-ai-textarea min-height="110" show-submit="false" show-commands="false" show-agent="false" placeholder="For example: explain the rollout sequence more clearly and add knowledge checks."></robos-ai-textarea><div class="editor-actions"><button data-preview disabled>Preview update</button><button data-save hidden>Save course update</button><button data-discard hidden>Discard preview</button></div><p data-status role="status" aria-live="polite"></p><div data-preview-course></div></details>';
  const input=host.querySelector('robos-ai-textarea'),preview=host.querySelector('[data-preview]'),save=host.querySelector('[data-save]'),discard=host.querySelector('[data-discard]'),status=host.querySelector('[data-status]');let pending=null,busy=false;
  const changed=()=>{preview.disabled=busy||!input.value?.trim();if(pending){pending=null;save.hidden=discard.hidden=true;host.querySelector('[data-preview-course]').replaceChildren();}};
  input.addEventListener('input',changed);input.addEventListener('change',changed);
  const update=async()=>{if(preview.disabled)return;busy=true;preview.disabled=true;preview.textContent='Generating preview…';status.textContent='Codex is updating the course…';input.setAttribute('disabled','');try{const instruction=input.value;pending=await window.robosCourseEditor.preview({courseId:this.course['@id'],graphRoot:this.graphRoot,prompt:instruction});if(input.value!==instruction){pending=null;throw Error('The prompt changed during generation. Preview the updated prompt before saving.');}const sample=document.createElement('robos-elearning-player');sample.setAttribute('preview','');sample.setAttribute('embedded','');host.querySelector('[data-preview-course]').replaceChildren(sample);sample.course=pending.course;save.hidden=discard.hidden=false;status.textContent='Preview ready. Review the revised sections, then save or discard.';}catch(e){status.textContent=e.message;}finally{busy=false;preview.disabled=!input.value?.trim();preview.textContent='Preview update';input.removeAttribute('disabled');}};
  preview.onclick=update;input.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();update();}});
  save.onclick=async()=>{if(!pending)return;save.disabled=true;try{await window.robosCourseEditor.apply(pending.id);const course=pending.course;this.course=course;this.dispatchEvent(new CustomEvent('course-updated',{detail:{course},bubbles:true}));}catch(e){status.textContent=e.message;}finally{save.disabled=false;}};
  discard.onclick=()=>{pending=null;save.hidden=discard.hidden=true;host.querySelector('[data-preview-course]').replaceChildren();status.textContent='Preview discarded. The saved course is unchanged.';};
 }
 render(){const root=this.shadowRoot;root.innerHTML=`<style>:host{display:block;color:#dce8f1;font:15px/1.7 system-ui}*{box-sizing:border-box}header{display:flex;justify-content:space-between;gap:20px;padding:12px 0 18px;border-bottom:1px solid #304453}h2{font-size:20px;margin:0}h3{font-size:17px;margin:22px 0 10px}p{margin:12px 0}.course-editor{border:1px solid #304453;border-radius:6px;padding:12px 16px;margin:16px 0}.course-editor summary{cursor:pointer;color:#9fd6e8}.editor-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}[hidden]{display:none!important}nav{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}button{font:inherit;color:#cee8f5;background:#172c3b;border:1px solid #38566b;padding:8px 12px;border-radius:5px;cursor:pointer}button[aria-current=step]{border-color:#62c5e5;background:#20465a}button:disabled{opacity:.4;cursor:default}article{max-width:1000px;padding:8px 0}pre{white-space:pre-wrap;background:#080f15;padding:16px;overflow:auto}code{font-family:monospace}a{color:#78cee9}img{max-width:100%}ul,ol{padding-left:25px}label{display:flex;align-items:baseline;gap:10px;margin:12px 0;cursor:pointer}input{accent-color:#54bed7}.reflection{border-left:2px solid #47778d;padding:8px 18px;color:#bdd7e3}.feedback{color:#9bcede}footer{display:flex;justify-content:space-between;border-top:1px solid #304453;padding-top:18px;margin-top:22px}small{color:#9eb4c3}fieldset{border:1px solid #304453;margin:16px 0;padding:14px}legend{padding:0 8px}select{max-width:100%;width:100%;background:#172c3b;color:#cee8f5;border:1px solid #38566b;padding:10px;font:inherit;border-radius:5px}:host([embedded]) header h2{display:none}:host([embedded]) header{padding-top:0}button:focus-visible,input:focus-visible{outline:2px solid #5ed4ef;outline-offset:2px}@media(max-width:600px){header{display:block}nav{display:grid;grid-template-columns:1fr}}</style><header><h2></h2><small role="status"></small></header><div data-editor></div><nav aria-label="Course sections"></nav><article></article><footer><button data-prev>Previous</button><button data-next>Next</button></footer>`;
 if(!this._course){root.querySelector('h2').textContent='No course loaded';return;}root.querySelector('h2').textContent=this._course['dcterms:title'];const nav=root.querySelector('nav'),select=document.createElement('select');select.setAttribute('aria-label','Course section');nav.append(select);this.modules.forEach((m,i)=>{const option=document.createElement('option');option.value=String(i);option.textContent=(i+1)+'. '+(this.complete(i)?'✓ ':'')+m.title;select.append(option);});select.value=String(this.index);select.onchange=()=>{this.index=Number(select.value);this.render();};this.editor();const m=this.modules[this.index],body=root.querySelector('article');if(!m){body.textContent='This course has no sections.';return;}this.text('h3',m.title,body);this.markdown(m.markdown||m.overview||'',body);
 if(m.reflection)this.text('p',m.reflection,body).className='reflection';
 const checkbox=(label,key)=>{const row=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.disabled=this.hasAttribute('preview');box.checked=!!this.state[key];box.onchange=()=>{this.state[key]=box.checked;this.save();};row.append(box,document.createTextNode(label));body.append(row);};
 if(m.labSteps?.length){this.text('h3','Lab steps',body);m.labSteps.forEach((step,j)=>checkbox(step,'lab:'+this.index+':'+j));}
 for(const [j,q] of (m.quiz||[]).entries()){const field=document.createElement('fieldset');this.text('legend',q.question,field);const feedback=document.createElement('p');feedback.className='feedback';const key='quiz:'+this.index+':'+j;for(const option of q.options||[]){const row=document.createElement('label'),radio=document.createElement('input');radio.type='radio';radio.disabled=this.hasAttribute('preview');radio.name='quiz-'+j;radio.value=option;radio.checked=this.state['answer:'+this.index+':'+j]===option;radio.onchange=()=>{const correct=option===q.answer;this.state[key]=correct;this.state['answer:'+this.index+':'+j]=option;feedback.textContent=correct?'Correct. '+(q.explanation||''):'Review this section and try again.';this.save();};row.append(radio,document.createTextNode(option));field.append(row);}if(this.state[key])feedback.textContent='Correct. '+(q.explanation||'');field.append(feedback);body.append(field);}
 checkbox('I have reviewed this section','read:'+this.index);const prev=root.querySelector('[data-prev]'),next=root.querySelector('[data-next]');prev.disabled=this.index===0;next.disabled=this.index===this.modules.length-1;prev.onclick=()=>{this.index--;this.render();};next.onclick=()=>{this.index++;this.render();};this.updateProgress();
 }
}
customElements.define('robos-elearning-player',RobOSElearningPlayer);
