'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const catalog=[['code','VS Code','code','vscode'],['cursor','Cursor','cursor','vscode'],['windsurf','Windsurf','windsurf','vscode'],['idea','IntelliJ IDEA','idea','jetbrains'],['webstorm','WebStorm','webstorm','jetbrains'],['pycharm','PyCharm','pycharm','jetbrains'],['goland','GoLand','goland','jetbrains'],['clion','CLion','clion','jetbrains'],['rider','Rider','rider','jetbrains'],['rustrover','RustRover','rustrover','jetbrains'],['datagrip','DataGrip','datagrip','jetbrains'],['phpstorm','PhpStorm','phpstorm','jetbrains'],['rubymine','RubyMine','rubymine','jetbrains'],['zed','Zed','zed','folder'],['sublime','Sublime Text','subl','folder']].map(([id,name,cmd,family])=>({id,name,cmd,family}));
const config=()=>path.join(os.homedir(),'.config/robos');
function read(file,fallback){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch(e){if(e.code==='ENOENT')return fallback;throw e;}}
function projects(){return read(path.join(config(),'git-projects.json'),{projects:[]}).projects;}
function normalize(url){return String(url||'').replace(/^git@github.com:/,'https://github.com/').replace(/\.git\/?$/,'').replace(/\/$/,'').toLowerCase();}
function preferred(project){const settings=read(path.join(config(),'settings.json'),{});const id=project?.ideId||settings.default_ide;return catalog.find(i=>i.id===({vscode:'code',intellij:'idea'}[id]||id))||null;}
function executable(ide){const names=[ide.cmd,...(ide.id==='idea'?['intellij-idea','idea.sh']:ide.id==='pycharm'?['pycharm-community','pycharm.sh']:[ide.cmd+'.sh'])];for(const name of names){try{return cp.execFileSync('which',[name],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();}catch{}}return null;}
function installed(){return catalog.map(ide=>({...ide,available:!!executable(ide)}));}
function choicesFor(selected,{availability=installed(),defaultIDE=preferred(null)}={}){
 const matches=new Map(),missing=[];
 for(const project of selected){const name=project.label||project.name||project.repo||project.url;const add=(id,scope)=>{const ide=catalog.find(i=>i.id===id);if(!ide)return;const item=matches.get(id)||{...ide,available:!!availability.find(i=>i.id===id)?.available,projects:[]};if(!item.projects.includes(scope))item.projects.push(scope);matches.set(id,item);};
 const primary=project.ideId||defaultIDE?.id;if(primary)add(primary,name);
 for(const root of project.projectRoots||[])if(root.ideId)add(root.ideId,name+' / '+root.relativePath);
 if(!primary&&!(project.projectRoots||[]).some(r=>r.ideId))missing.push(name);
 }
 return {choices:[...matches.values()].sort((a,b)=>a.name.localeCompare(b.name)),missing};
}
function localChoices(id){const project=projects().find(p=>p.id===id);if(!project)throw Error('Unknown Git project');return choicesFor([project]);}
function selectIDE(options,id){if(options.missing.length)throw Error('Assign an IDE in Git Projects for: '+options.missing.join(', '));if(!id&&options.choices.length!==1)throw Error('Choose an IDE for this workspace.');const ide=options.choices.find(i=>i.id===(id||options.choices[0]?.id));if(!ide)throw Error('This IDE is not associated with the workspace’s Git projects.');if(!ide.available)throw Error(ide.name+' is not installed. Install it in RobOS Software Center.');return ide;}
function associate(id,ideId,dependsOn,projectRoots){if(!catalog.some(i=>i.id===ideId))throw Error('Choose an IDE.');const file=path.join(config(),'git-projects.json'),data=read(file,{projects:[]}),project=data.projects.find(p=>p.id===id);if(!project)throw Error('Git project no longer exists.');if(dependsOn!==undefined){if(!Array.isArray(dependsOn)||dependsOn.some(url=>!data.projects.some(p=>normalize(p.url)===normalize(url))||normalize(url)===normalize(project.url)))throw Error('Choose dependencies from other registered Git projects.');project.dependsOn=[...new Set(dependsOn)];}if(projectRoots!==undefined){if(!Array.isArray(projectRoots)||projectRoots.some(r=>typeof r.relativePath!=='string'||path.isAbsolute(r.relativePath)||r.relativePath.split(/[\\/]/).includes('..')||!catalog.some(i=>i.id===r.ideId)))throw Error('Invalid project root association.');project.projectRoots=projectRoots;}project.ideId=ideId;project.updatedAt=Date.now();const temp=file+'.'+process.pid+'.tmp';fs.writeFileSync(temp,JSON.stringify(data,null,2));fs.renameSync(temp,file);return project;}
async function launch(ideId,target){const ide=catalog.find(i=>i.id===ideId);if(!ide)throw Error('Associate this Git project with an IDE first.');await new Promise((resolve,reject)=>{const child=cp.spawn(executable(ide)||ide.cmd,ide.family==='vscode'?['--new-window',target]:[target],{detached:true,stdio:'ignore'});child.once('error',()=>reject(Error(`${ide.name} could not start. Install its command-line launcher (${ide.cmd}) or change the Git project IDE association.`)));child.once('spawn',()=>{child.unref();resolve();});});return {ok:true,ide:ide.name,target};}
async function attachWorkspace(id,root){const real=fs.realpathSync(root),file=path.join(config(),'git-projects.json'),data=read(file,{projects:[]}),project=data.projects.find(p=>p.id===id);if(!project)throw Error('Unknown Git project');const origin=(await require('../robos-agent-client/work-task/core').command('git',['-C',real,'remote','get-url','origin'])).trim();if(normalize(origin)!==normalize(project.url))throw Error('That workspace belongs to a different Git repository.');const top=(await require('../robos-agent-client/work-task/core').command('git',['-C',real,'rev-parse','--show-toplevel'])).trim();project.workspaces=[...new Set([...(project.workspaces||[]),top])];if(!project.localPath)project.localPath=top;fs.writeFileSync(file,JSON.stringify(data,null,2));return project;}
async function openLocal(id,root,ideId){const project=projects().find(p=>p.id===id);if(!project||![project.localPath,...project.workspaces||[]].includes(root))throw Error('Register this checkout in Git Projects first.');const ide=selectIDE(choicesFor([project]),ideId);const discovery=require('./project-roots'),roots=project.projectRoots?.length?project.projectRoots:discovery.discover(root).roots;const items=(roots.length?roots:[{relativePath:'.'}]).map(r=>({name:(project.repo||project.name)+'/'+r.relativePath,path:discovery.resolve(root,r.relativePath),gitRoot:root}));const hash=require('node:crypto').createHash('sha256').update(root).digest('hex').slice(0,16);const target=require('./ide-workspaces').writeWorkspace(path.join(config(),'ide-workspaces',hash,ide.id),items,ide,{name:project.label||project.repo||project.name});return launch(ide.id,target);}
module.exports={choicesFor,localChoices,selectIDE,catalog,projects,normalize,preferred,installed,associate,launch,attachWorkspace,openLocal,executable};
