'use strict';
// Read-only discovery: manifests are data; no package-manager scripts or plugins run.
const fs=require('node:fs'),path=require('node:path');
const excluded=new Set(['.git','node_modules','vendor','.venv','venv','dist','build','target','.next','.cache','.idea','.vscode','coverage','bazel-out','bazel-bin','bazel-testlogs']);
const markers={'package.json':['javascript','webstorm'],'go.mod':['go','goland'],'Cargo.toml':['rust','rustrover'],'pom.xml':['java','idea'],'build.gradle':['java','idea'],'build.gradle.kts':['kotlin','idea'],'pyproject.toml':['python','pycharm'],'setup.py':['python','pycharm'],'CMakeLists.txt':['cpp','clion'],'composer.json':['php','phpstorm'],'Gemfile':['ruby','rubymine'],'Chart.yaml':['helm','idea'],'MODULE.bazel':['bazel','idea'],'WORKSPACE':['bazel','idea'],'WORKSPACE.bazel':['bazel','idea']};
function fromFiles(files){const roots=new Map();for(const file of files){if(typeof file!=='string'||path.isAbsolute(file)||file.split('/').some(p=>p==='..'||excluded.has(p)||p.startsWith('bazel-')))continue;const name=path.posix.basename(file),type=markers[name]||(/\.(csproj|fsproj|sln)$/.test(name)?['dotnet','rider']:null);if(!type)continue;const root=path.posix.dirname(file);if(!roots.has(root))roots.set(root,{relativePath:root,types:[],markers:[],ideId:type[1]});const item=roots.get(root);item.markers.push(file);if(!item.types.includes(type[0]))item.types.push(type[0]);if(type[0]==='go'||type[0]==='rust')item.ideId=type[1];}return [...roots.values()].sort((a,b)=>a.relativePath.localeCompare(b.relativePath));}
function discover(root,{maxDepth=10,maxEntries=50000}={}){const files=[];let count=0,truncated=false;const walk=(dir,relative,depth)=>{if(depth>maxDepth){truncated=true;return;}for(const entry of fs.readdirSync(dir,{withFileTypes:true})){if(++count>maxEntries){truncated=true;return;}if(entry.isSymbolicLink()||excluded.has(entry.name)||entry.name.startsWith('bazel-'))continue;const rel=relative?relative+'/'+entry.name:entry.name;if(entry.isDirectory())walk(path.join(dir,entry.name),rel,depth+1);else if(entry.isFile())files.push(rel);}};walk(root,'',0);return {roots:fromFiles(files),truncated};}
function resolve(root,relative){if(typeof relative!=='string'||path.isAbsolute(relative)||relative.split(/[\\/]/).includes('..'))throw Error('Project roots must be relative to the repository.');const full=path.resolve(root,relative),realRoot=fs.realpathSync(root),real=fs.realpathSync(full);if(real!==realRoot&&!real.startsWith(realRoot+path.sep))throw Error('Project root leaves the repository.');return real;}
module.exports={discover,fromFiles,resolve};
