'use strict';
let servers=[],providers={},editing=null;const $=id=>document.getElementById(id),status=$('status');
async function call(name,input){const r=await window.ci[name](input);if(!r.ok)throw Error(r.error);return r.data;}
async function refresh(){const data=await call('list');servers=data.servers;providers=data.providers;$('provider').replaceChildren(...Object.entries(providers).map(([id,name])=>new Option(name,id)));if(!$('graph-root').value)$('graph-root').value=data.graphRoot;$('servers').replaceChildren();for(const s of servers){const tr=document.createElement('tr');for(const value of [s.name,providers[s.provider],s.url]){const td=document.createElement('td');td.textContent=value;tr.append(td);}const updated=document.createElement('td');updated.innerHTML=window.robosList.time(s.updatedAt);tr.append(updated);tr.dataset.listTitle=s.name;tr.dataset.listUpdated=s.updatedAt||'';const actions=document.createElement('td');for(const [label,handler] of [['Edit',()=>edit(s)],['Open',()=>call('open',s.id)],['Import repository',()=>importRepo(s)]]){const b=document.createElement('button');b.textContent=label;b.onclick=()=>Promise.resolve(handler()).catch(e=>status.textContent=e.message);actions.append(b,' ');}tr.append(actions);$('servers').append(tr);}if(!servers.length)status.textContent='No CI servers configured. Add your first server.';}
function edit(server){editing=server?.id||null;$('server-form').hidden=false;$('name').value=server?.name||'';$('provider').value=server?.provider||'buildkite';$('url').value=server?.url||'';$('credential').value=server?.credentialRef||'';if(server)$('graph-root').value=server.graphRoot||'';$('name').focus();}
$('new-server').onclick=()=>edit();$('cancel-edit').onclick=()=>$('server-form').hidden=true;
$('choose-graph').onclick=async()=>{const dir=await call('folder');if(dir)$('graph-root').value=dir;};
$('server-form').onsubmit=async e=>{e.preventDefault();try{await call('save',{id:editing,name:$('name').value,provider:$('provider').value,url:$('url').value,credentialRef:$('credential').value,graphRoot:$('graph-root').value});$('server-form').hidden=true;await refresh();status.textContent='Server saved. Import a repository to add it and its pipeline definitions to the graph.';}catch(e){status.textContent=e.message;}};
async function previewRepo(id,repositoryRoot){status.textContent='Reading tracked pipeline definitions…';$('preview').hidden=true;const data=await call('preview',{id,repositoryRoot});$('files').replaceChildren();for(const file of data.files){const li=document.createElement('li');li.textContent=file;$('files').append(li);}$('import-source').textContent=data.repository;$('preview').hidden=false;$('apply').disabled=!data.validation.conforms||data.unchanged;status.textContent=data.unchanged?'Already imported; the graph is up to date.':data.validation.conforms?`${data.files.length} pipeline definitions ready to import.`:data.validation.errors.join('\n');}
async function importRepo(server){const root=await call('folder');if(root)await previewRepo(server.id,root);}
$('cancel-import').onclick=()=>$('preview').hidden=true;$('apply').onclick=async()=>{$('apply').disabled=true;try{await call('apply');$('preview').hidden=true;status.textContent='Imported and validated in the knowledge graph.';}catch(e){status.textContent=e.message;}};
refresh().catch(e=>status.textContent=e.message);
