'use strict';
const { app, BrowserWindow, ipcMain } = require('electron');
const path = require('path');
const fs = require('fs');

let _debugServer;
try {
  _debugServer = require('/usr/local/share/robos/robos-lib/dom-snapshot');
} catch {
  try {
    _debugServer = require('../robos-lib/dom-snapshot');
  } catch {}
}

let mainWindow;

const DEFAULT_ENTITIES = {
  version: '1.0',
  activeEntity: 'form.typespec',
  entities: [
    {
      id: 'form.typespec',
      name: 'Dynamic Form Model',
      format: 'typespec',
      path: '.robos/entities/form.typespec',
      description: 'Canonical domain model for multi-step dynamic forms and validation rules',
      rawCode: `import "@typespec/http";
import "@typespec/rest";

using TypeSpec.Http;

namespace BuildBarn.Forms;

enum FormStatus {
  Draft,
  InProgress,
  UnderReview,
  Approved,
  Rejected
}

model DynamicForm {
  id: string;
  title: string;
  status: FormStatus;
  stepCount: int32;
  steps: FormStep[];
  vendorEin?: string;
  createdAt: utcDateTime;
  updatedAt: utcDateTime;
}

model FormStep {
  stepIndex: int32;
  stepTitle: string;
  isCompleted: boolean;
  fields: FormField[];
}

model FormField {
  fieldKey: string;
  fieldType: "text" | "number" | "boolean" | "file";
  value: string;
  isRequired: boolean;
}`,
      compiledTargets: {
        ts: `// Auto-generated by TypeSpec Compiler for TypeScript / Zod
import { z } from "zod";

export const FormStatusSchema = z.enum(["Draft", "InProgress", "UnderReview", "Approved", "Rejected"]);
export type FormStatus = z.infer<typeof FormStatusSchema>;

export const FormFieldSchema = z.object({
  fieldKey: z.string(),
  fieldType: z.enum(["text", "number", "boolean", "file"]),
  value: z.string(),
  isRequired: z.boolean(),
});
export type FormField = z.infer<typeof FormFieldSchema>;

export const FormStepSchema = z.object({
  stepIndex: z.number().int(),
  stepTitle: z.string(),
  isCompleted: z.boolean(),
  fields: z.array(FormFieldSchema),
});
export type FormStep = z.infer<typeof FormStepSchema>;

export const DynamicFormSchema = z.object({
  id: z.string(),
  title: z.string(),
  status: FormStatusSchema,
  stepCount: z.number().int(),
  steps: z.array(FormStepSchema),
  vendorEin: z.string().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
});
export type DynamicForm = z.infer<typeof DynamicFormSchema>;`,
        java: `// Auto-generated by TypeSpec Compiler for Java 21 / Jackson
package com.buildbarn.forms.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.List;

public enum FormStatus {
    Draft, InProgress, UnderReview, Approved, Rejected
}

public record FormField(
    @JsonProperty("fieldKey") String fieldKey,
    @JsonProperty("fieldType") String fieldType,
    @JsonProperty("value") String value,
    @JsonProperty("isRequired") boolean isRequired
) {}

public record FormStep(
    @JsonProperty("stepIndex") int stepIndex,
    @JsonProperty("stepTitle") String stepTitle,
    @JsonProperty("isCompleted") boolean isCompleted,
    @JsonProperty("fields") List<FormField> fields
) {}

public record DynamicForm(
    @JsonProperty("id") String id,
    @JsonProperty("title") String title,
    @JsonProperty("status") FormStatus status,
    @JsonProperty("stepCount") int stepCount,
    @JsonProperty("steps") List<FormStep> steps,
    @JsonProperty("vendorEin") String vendorEin,
    @JsonProperty("createdAt") Instant createdAt,
    @JsonProperty("updatedAt") Instant updatedAt
) {}`,
        python: `# Auto-generated by TypeSpec Compiler for Python / Pydantic v2
from enum import Enum
from typing import List, Optional
from datetime import datetime
from pydantic import BaseModel, Field

class FormStatus(str, Enum):
    Draft = "Draft"
    InProgress = "InProgress"
    UnderReview = "UnderReview"
    Approved = "Approved"
    Rejected = "Rejected"

class FormField(BaseModel):
    field_key: str = Field(alias="fieldKey")
    field_type: str = Field(alias="fieldType")
    value: str
    is_required: bool = Field(alias="isRequired")

class FormStep(BaseModel):
    step_index: int = Field(alias="stepIndex")
    step_title: str = Field(alias="stepTitle")
    is_completed: bool = Field(alias="isCompleted")
    fields: List[FormField]

class DynamicForm(BaseModel):
    id: str
    title: str
    status: FormStatus
    step_count: int = Field(alias="stepCount")
    steps: List[FormStep]
    vendor_ein: Optional[str] = Field(default=None, alias="vendorEin")
    created_at: datetime = Field(alias="createdAt")
    updated_at: datetime = Field(alias="updatedAt")`,
        go: `// Auto-generated by TypeSpec Compiler for Go 1.22
package dto

import "time"

type FormStatus string

const (
	FormStatusDraft       FormStatus = "Draft"
	FormStatusInProgress  FormStatus = "InProgress"
	FormStatusUnderReview FormStatus = "UnderReview"
	FormStatusApproved    FormStatus = "Approved"
	FormStatusRejected    FormStatus = "Rejected"
)

type FormField struct {
	FieldKey   string ` + '`' + `json:"fieldKey"` + '`' + `
	FieldType  string ` + '`' + `json:"fieldType"` + '`' + `
	Value      string ` + '`' + `json:"value"` + '`' + `
	IsRequired bool   ` + '`' + `json:"isRequired"` + '`' + `
}

type FormStep struct {
	StepIndex   int         ` + '`' + `json:"stepIndex"` + '`' + `
	StepTitle   string      ` + '`' + `json:"stepTitle"` + '`' + `
	IsCompleted bool        ` + '`' + `json:"isCompleted"` + '`' + `
	Fields      []FormField ` + '`' + `json:"fields"` + '`' + `
}

type DynamicForm struct {
	ID        string     ` + '`' + `json:"id"` + '`' + `
	Title     string     ` + '`' + `json:"title"` + '`' + `
	Status    FormStatus ` + '`' + `json:"status"` + '`' + `
	StepCount int        ` + '`' + `json:"stepCount"` + '`' + `
	Steps     []FormStep ` + '`' + `json:"steps"` + '`' + `
	VendorEin *string    ` + '`' + `json:"vendorEin,omitempty"` + '`' + `
	CreatedAt time.Time  ` + '`' + `json:"createdAt"` + '`' + `
	UpdatedAt time.Time  ` + '`' + `json:"updatedAt"` + '`' + `
}`,
        prisma: `// Auto-generated by TypeSpec Compiler for Prisma ORM
enum FormStatus {
  Draft
  InProgress
  UnderReview
  Approved
  Rejected
}

model DynamicForm {
  id        String     @id @default(uuid())
  title     String
  status    FormStatus @default(Draft)
  stepCount Int
  vendorEin String?
  steps     FormStep[]
  createdAt DateTime   @default(now())
  updatedAt DateTime   @updatedAt
}

model FormStep {
  id          String      @id @default(uuid())
  formId      String
  form        DynamicForm @relation(fields: [formId], references: [id], onDelete: Cascade)
  stepIndex   Int
  stepTitle   String
  isCompleted Boolean     @default(false)
  fields      Json
}`,
        mock: `{
  "id": "form-2026-xyz892",
  "title": "Vendor Onboarding & Tax Certification",
  "status": "UnderReview",
  "stepCount": 3,
  "vendorEin": "XX-XXX8921",
  "steps": [
    {
      "stepIndex": 1,
      "stepTitle": "Company Information",
      "isCompleted": true,
      "fields": [
        { "fieldKey": "legalName", "fieldType": "text", "value": "Acme Global Seller LLC", "isRequired": true },
        { "fieldKey": "taxYear", "fieldType": "number", "value": "2026", "isRequired": true }
      ]
    },
    {
      "stepIndex": 2,
      "stepTitle": "Tax Forms Upload",
      "isCompleted": true,
      "fields": [
        { "fieldKey": "form1099Uri", "fieldType": "file", "value": "s3://tax-vault/2026/1099-misc.pdf", "isRequired": true }
      ]
    },
    {
      "stepIndex": 3,
      "stepTitle": "Signature & Sign-Off",
      "isCompleted": false,
      "fields": [
        { "fieldKey": "signedBy", "fieldType": "text", "value": "Nick D. (Lead Architect)", "isRequired": true }
      ]
    }
  ],
  "createdAt": "2026-09-03T12:00:00Z",
  "updatedAt": "2026-09-03T13:30:00Z"
}`,
      },
    },
    {
      id: 'user.typespec',
      name: 'User Account Model',
      format: 'typespec',
      path: '.robos/entities/user.typespec',
      description: 'Identity and role-based access control domain model',
      rawCode: `import "@typespec/http";

namespace BuildBarn.Identity;

enum UserRole {
  Admin,
  Architect,
  Developer,
  AgentWorker
}

model User {
  id: string;
  email: string;
  displayName: string;
  roles: UserRole[];
  isActive: boolean;
  createdAt: utcDateTime;
}`,
      compiledTargets: {
        ts: `export interface User { id: string; email: string; displayName: string; roles: ("Admin" | "Architect" | "Developer" | "AgentWorker")[]; isActive: boolean; createdAt: string; }`,
        java: `public record User(String id, String email, String displayName, List<String> roles, boolean isActive, Instant createdAt) {}`,
        python: `class User(BaseModel): id: str; email: str; display_name: str; roles: List[str]; is_active: bool; created_at: datetime`,
        go: `type User struct { ID string; Email string; DisplayName string; Roles []string; IsActive bool; CreatedAt time.Time }`,
        prisma: `model User { id String @id; email String @unique; displayName String; isActive Boolean; createdAt DateTime }`,
        mock: `{ "id": "usr-1", "email": "ndipiazza@robos.dev", "displayName": "Nick D.", "roles": ["Architect"], "isActive": true }`,
      },
    },
  ],
};

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 820,
    backgroundColor: '#0d1117',
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextBridge: true,
      nodeIntegration: false,
    },
  });

  mainWindow.loadFile(path.join(__dirname, 'renderer', 'index.html'));

  if (_debugServer && _debugServer.startDebugServer) {
    _debugServer.startDebugServer(mainWindow, 19164);
  }
}

let activeBranch = 'main';

const BRANCH_CATALOG = {
  'main': {
    name: 'main',
    commit: '8f9a2b1',
    clean: true,
    label: '🌿 main (Production / GitOps HEAD)',
    rawCodeOverlay: `import "@typespec/http";
import "@typespec/rest";

using TypeSpec.Http;

namespace BuildBarn.Forms;

enum FormStatus {
  Draft,
  InProgress,
  UnderReview,
  Approved,
  Rejected
}

model DynamicForm {
  id: string;
  title: string;
  status: FormStatus;
  stepCount: int32;
  steps: FormStep[];
  createdAt: utcDateTime;
  updatedAt: utcDateTime;
}

model FormStep {
  stepIndex: int32;
  stepTitle: string;
  isCompleted: boolean;
  fields: FormField[];
}

model FormField {
  fieldKey: string;
  fieldType: "text" | "number" | "boolean" | "file";
  value: string;
  isRequired: boolean;
}`,
  },
  'feature/TAX-1099-ein-verification': {
    name: 'feature/TAX-1099-ein-verification',
    commit: 'd4e5f6a',
    clean: false,
    label: '🌿 feature/TAX-1099-ein-verification (EIN Delta)',
    rawCodeOverlay: `import "@typespec/http";
import "@typespec/rest";

using TypeSpec.Http;

namespace BuildBarn.Forms;

enum FormStatus {
  Draft,
  InProgress,
  UnderReview,
  Approved,
  Rejected
}

model DynamicForm {
  id: string;
  title: string;
  status: FormStatus;
  stepCount: int32;
  steps: FormStep[];
  vendorEin?: string; // [GitOps Delta: TAX-1099]
  taxCertificationUri?: string; // [GitOps Delta: TAX-1099]
  createdAt: utcDateTime;
  updatedAt: utcDateTime;
}

model FormStep {
  stepIndex: int32;
  stepTitle: string;
  isCompleted: boolean;
  fields: FormField[];
}

model FormField {
  fieldKey: string;
  fieldType: "text" | "number" | "boolean" | "file";
  value: string;
  isRequired: boolean;
}`,
  },
  'hotfix/calc-rate': {
    name: 'hotfix/calc-rate',
    commit: 'e2b1c4f',
    clean: true,
    label: '🌿 hotfix/calc-rate',
    rawCodeOverlay: null,
  },
};

ipcMain.handle('schema-get-entities', async () => {
  return {
    ...DEFAULT_ENTITIES,
    activeBranch,
    branches: Object.values(BRANCH_CATALOG).map(b => ({ name: b.name, commit: b.commit, label: b.label })),
  };
});

ipcMain.handle('schema-list-branches', async () => {
  return Object.values(BRANCH_CATALOG);
});

ipcMain.handle('schema-switch-branch', async (_evt, branchName) => {
  if (BRANCH_CATALOG[branchName]) {
    activeBranch = branchName;
    const branchInfo = BRANCH_CATALOG[branchName];
    const formEntity = DEFAULT_ENTITIES.entities.find(e => e.id === 'form.typespec');
    if (formEntity && branchInfo.rawCodeOverlay) {
      formEntity.rawCode = branchInfo.rawCodeOverlay;
    }
    return { ok: true, activeBranch, branchInfo };
  }
  return { ok: false, message: 'Branch not found' };
});

ipcMain.handle('schema-compile-targets', async (_evt, entityId) => {
  const entity = DEFAULT_ENTITIES.entities.find(e => e.id === entityId) || DEFAULT_ENTITIES.entities[0];
  return {
    ok: true,
    entityId: entity.id,
    durationMs: 48,
    targetsCompiled: ['TypeScript', 'Java', 'Python', 'Go', 'Prisma', 'MockJSON'],
    diagnostics: '0 compilation errors, 0 warnings',
  };
});

ipcMain.handle('schema-detect-breaking', async (_evt, entityId) => {
  return {
    ok: true,
    entityId,
    breakingChangesCount: 0,
    isBackwardCompatible: true,
    auditReport: 'Buf Breaking & TypeSpec Drift Check: 100% Backward Compatible (0 Field Drift Violations)',
  };
});

app.whenReady().then(createWindow);

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') app.quit();
});
