const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gp', {
  readProjects:  ()              => ipcRenderer.invoke('read-projects'),
  writeProjects: (data)          => ipcRenderer.invoke('write-projects', data),
  parseUrl:      (url)           => ipcRenderer.invoke('parse-url', url),
  checkCloned:   (localPath)     => ipcRenderer.invoke('check-cloned', localPath),
  clone:         (url, lp)       => ipcRenderer.invoke('clone', { url, localPath: lp }),
  pull:          (lp)            => ipcRenderer.invoke('pull', { localPath: lp }),
  openVsCode:         (lp)                              => ipcRenderer.invoke('open-vscode', lp),
  openVsCodeScript:   (projectId, script, type)         => ipcRenderer.invoke('open-vscode-script', { projectId, script, type }),
  getInstalledIDEs:   ()                                => ipcRenderer.invoke('get-installed-ides'),
  openInIDE:          (cmd, lp)                         => ipcRenderer.invoke('open-in-ide', { cmd, localPath: lp }),
  openTerminal:  (lp)            => ipcRenderer.invoke('open-terminal', lp),
  openBrowser:   (url)           => ipcRenderer.invoke('open-browser', url),
  getBranches:   (lp)            => ipcRenderer.invoke('get-branches', lp),
  getLog:        (lp)            => ipcRenderer.invoke('get-log', lp),
  onCloneOutput: (cb)            => ipcRenderer.on('clone-output', (_, d) => cb(d)),
  listGhRepos:   ()              => ipcRenderer.invoke('list-gh-repos'),
  searchGhRepos: (q)             => ipcRenderer.invoke('search-gh-repos', { query: q }),
  runDevSetup:   (lp, script)    => ipcRenderer.invoke('run-dev-setup', { localPath: lp, script }),
  openInExplorer:(lp)            => ipcRenderer.invoke('open-in-explorer', lp),
  aiFixScript:        (lp, url, script, err, type)     => ipcRenderer.invoke('ai-fix-devsetup-script', { localPath: lp, repoUrl: url, script, errorOutput: err, type }),
  aiDevSetupStep:     (lp, url, p, step)                  => ipcRenderer.invoke('ai-dev-setup-step', { localPath: lp, repoUrl: url, extraPrompt: p, step }),
  aiDevSetupInterview:(lp, url, p)                      => ipcRenderer.invoke('ai-dev-setup-interview', { localPath: lp, repoUrl: url, extraPrompt: p }),
  aiRefineDevSetup:   (lp, url, field, current, feedback) => ipcRenderer.invoke('ai-refine-devsetup', { localPath: lp, repoUrl: url, field, current, feedback }),
  aiDetectSecrets: (lp, url)     => ipcRenderer.invoke('ai-detect-secrets', { localPath: lp, repoUrl: url }),
  listPath:        (prefix)      => ipcRenderer.invoke('list-path', prefix),
  listGroups:      ()            => ipcRenderer.invoke('list-groups'),
  listOrgRepos:    (org)         => ipcRenderer.invoke('list-org-repos', org),
  listAIProviders: ()            => ipcRenderer.invoke('gp-list-ai-providers'),
  aiCreateRepos:   (prompt, pid) => ipcRenderer.invoke('gp-ai-create-repos', { prompt, providerId: pid || null }),
  onIntellijWait: (cb) => ipcRenderer.on('intellij-wait', (_, info) => cb(info)),
  runInIntellij:   (projectId, projectPath, scripts, scriptKey) => ipcRenderer.invoke('run-in-intellij', { projectId, projectPath, scripts, scriptKey }),
  logsSearch:      (opts)        => ipcRenderer.invoke('logs-search', opts),
  logsListApps:    ()            => ipcRenderer.invoke('logs-list-apps'),
});
