const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('robosProviders',{list:options=>ipcRenderer.invoke('ci-recovery-providers',options)});
contextBridge.exposeInMainWorld('api', {
  ciRecoveryState:()=>ipcRenderer.invoke('ci-recovery-state'),
  ciRecoveryAction:input=>ipcRenderer.invoke('ci-recovery-action',input),
  openAgentSession:input=>ipcRenderer.invoke('open-agent-session',input),
  reviewCIStatus:()=>ipcRenderer.invoke('review-ci-status'),
  reviewIDEs:()=>ipcRenderer.invoke('review-ides'),
  openReviewIDE:id=>ipcRenderer.invoke('review-open-ide',id),
  listSkills:()=>ipcRenderer.invoke('robos-skills-list'),
  getDemoState: () => ipcRenderer.invoke('demo-state'),
  demoAction: opts => ipcRenderer.invoke('demo-action', opts),
  openDemoSessionFile: () => ipcRenderer.invoke('demo-open-session-file'),
  getDemoHistory: before => ipcRenderer.invoke('demo-history', before),
  clearDemoChat: () => ipcRenderer.invoke('demo-clear-chat'),
  saveDemoProcess: value => ipcRenderer.invoke('demo-save-process', value),
  onDemoState: callback => { const listener = (_, state) => callback(state); ipcRenderer.on('demo-state', listener); return () => ipcRenderer.removeListener('demo-state', listener); },
  reviewMessageMembers: serverId => ipcRenderer.invoke('review-message-members', serverId),
  reviewMessageOptions: () => ipcRenderer.invoke('review-message-options'),
  reviewMessageChannels: serverId => ipcRenderer.invoke('review-message-channels', serverId),
  sendReviewMessage: input => ipcRenderer.invoke('review-message-send', input),
  reviewEvidenceImage: id => ipcRenderer.invoke('review-evidence-image',id),
  onPublishProgress: callback => { const handler=(_,text)=>callback(text);ipcRenderer.on('review-publish-progress',handler);return ()=>ipcRenderer.removeListener('review-publish-progress',handler); },
  generatePRDescription: input => ipcRenderer.invoke('generate-pr-description', input),
  onDescriptionProgress: cb => {const listener=(_,text)=>cb(text);ipcRenderer.on('review-description-progress',listener);return ()=>ipcRenderer.removeListener('review-description-progress',listener);},
  refreshReviewPR:()=>ipcRenderer.invoke('refresh-review-pr'),
  updateReviewPR:input=>ipcRenderer.invoke('update-review-pr',input),
  reviewAdjustmentStatus:()=>ipcRenderer.invoke('review-adjustment-status'),
  pushReviewAdjustments:()=>ipcRenderer.invoke('push-review-adjustments'),
  createReviewPR: input => ipcRenderer.invoke('create-review-pr', input),
  getLocalReview: () => ipcRenderer.invoke('get-local-review'),
  getConfig:             ()     => ipcRenderer.invoke('get-config'),
  fetchPRs:              (opts) => ipcRenderer.invoke('fetch-prs', opts),
  fetchPRDetail:         (opts) => ipcRenderer.invoke('fetch-pr-detail', opts),
  submitReview:          (opts) => ipcRenderer.invoke('submit-review', opts),
  aiReviewSummary:       (opts) => ipcRenderer.invoke('ai-review-summary', opts),
  aiReviewChat:          (opts) => ipcRenderer.invoke('ai-review-chat', opts),
  fetchKGraphBranchDiff: (opts) => ipcRenderer.invoke('fetch-kgraph-branch-diff', opts),
  interactiveReview:     (opts) => ipcRenderer.invoke('interactive-review', opts),
  openInIntelliJ:        (opts) => ipcRenderer.invoke('open-in-intellij', opts),
  openInVSCode:          (opts) => ipcRenderer.invoke('open-in-vscode', opts),
  getIDEStatus:          ()     => ipcRenderer.invoke('get-ide-status'),
  openUrl:               (url)  => ipcRenderer.invoke('open-url', url),
  // PR Review Theater
  fetchPRTheaterContext: (opts) => ipcRenderer.invoke('fetch-pr-theater-context', opts),
  fetchPRDiffContent:    (opts) => ipcRenderer.invoke('fetch-pr-diff-content', opts),
  verifyPRTheaterQuiz:   (opts) => ipcRenderer.invoke('verify-pr-theater-quiz', opts),
  launchIDEBranchDiff:   (opts) => ipcRenderer.invoke('launch-ide-branch-diff', opts),
  submitPRTheaterReview: (opts) => ipcRenderer.invoke('submit-pr-theater-review', opts),
  executePRRestCall:     (opts) => ipcRenderer.invoke('execute-pr-rest-call', opts),
  launchIDEBreakpointSession: (opts) => ipcRenderer.invoke('launch-ide-breakpoint-session', opts),
  resumeIDEBreakpointSession: (opts) => ipcRenderer.invoke('resume-ide-breakpoint-session', opts),
  openAppELearning:      (opts) => ipcRenderer.invoke('open-app-elearning', opts),
  getPRTheaterConfig:    (opts) => ipcRenderer.invoke('get-pr-theater-config', opts),
  savePRTheaterConfig:   (opts) => ipcRenderer.invoke('save-pr-theater-config', opts),
  runAgentShowFix:       (opts) => ipcRenderer.invoke('run-agent-show-fix', opts),
  resumeAgentShowFixHandoff: (opts) => ipcRenderer.invoke('resume-agent-show-fix-handoff', opts),
});

