const {test}=require('node:test');const assert=require('node:assert/strict');const {createTheater,parseDiff}=require('./real-theater');
const url='https://github.com/org/repo/pull/1';
const context=async()=>({pr:{url,number:1,title:'Real change',body:'Evidence',headRefOid:'abc',baseRefName:'main',headRefName:'topic',files:[{path:'doc.md',additions:1,deletions:0}],statusCheckRollup:[]},diff:'diff --git a/doc.md b/doc.md\n--- a/doc.md\n+++ b/doc.md\n@@ -0,0 +1 @@\n+Document\n',questions:[{label:'Target?',options:['main','topic'],answer:'main'}]});
const gates={docsReviewed:true,diffsInspected:true,evidenceReviewed:true};
const input=c=>({repo:'org/repo',number:1,reviewId:c.reviewId,action:'approve',gates});
test('diff available before quiz; quiz follows review and wrong answers fail',async()=>{const t=createTheater({context});const c=await t.load({repo:'org/repo',number:1});assert.equal(c.fileDiffs[0].hunks[0].lines[0].text,'Document');assert.throws(()=>t.quiz({courseId:c.reviewId,answers:{q0:0}}),/before taking/);assert(!t.quiz({courseId:c.reviewId,answers:{},gates}).passed);assert(t.quiz({courseId:c.reviewId,answers:{q0:0},gates}).passed);});
test('optional certificate allows merge after review without quiz, but never without evidence',async()=>{let calls=0;const t=createTheater({context,policy:()=>({requireCompletionCertificate:false}),merge:async()=>{calls++;return {state:'MERGED'};}});const c=await t.load({repo:'org/repo',number:1});await assert.rejects(t.submit({...input(c),gates:{}}),/documentation/);await assert.rejects(t.submit({...input(c),number:2}),/Load this PR/);assert.equal(calls,0);assert((await t.submit(input(c))).merged);assert.equal(calls,1);});
test('required certificate enforced server-side and current policy rechecked at merge',async()=>{let required=false,calls=0;const t=createTheater({context,policy:()=>({requireCompletionCertificate:required}),merge:async()=>{calls++;return {state:'MERGED'};}});const c=await t.load({repo:'org/repo',number:1});required=true;await assert.rejects(t.submit(input(c)),/requires a passed knowledge check/);assert.equal(calls,0);t.quiz({courseId:c.reviewId,answers:{q0:0},gates});assert((await t.submit(input(c))).merged);});
test('binary files do not produce invented hunks',()=>assert.deepEqual(parseDiff('Binary files differ',[{path:'a.png',additions:0,deletions:0}])[0].hunks,[]));
