'use strict';
const assert=require('node:assert/strict');
async function evaluate(js){const r=await fetch('http://localhost:19133/eval',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({js})});const data=await r.json();if(data.error)throw Error(data.error);return data.result;}
(async()=>{try{
 const state=await evaluate(`(()=>{const entries=[['mcp','Sign in with Chrome'],['slack','Reconnect Slack'],['agent','Open AGY sign-in']].map(([kind,label],i)=>({id:'ui-auth-preview-'+i,title:'UI verification: '+kind+' login',body:'Temporary rendering fixture; no credentials changed.',category:'agent',tier:'warning',ts:new Date().toISOString(),read:false,authStatus:'login-required',action:{type:'auth-reconcile',kind,serverId:'fixture',label}}));renderNotifications(entries);return {buttons:[...document.querySelectorAll('[data-auth-reconcile]')].map(b=>b.textContent),checks:document.querySelectorAll('[data-auth-check]').length};})()`);
 assert.deepEqual(state.buttons,['Sign in with Chrome','Reconnect Slack','Open AGY sign-in']);assert.equal(state.checks,2);
 const resolved=await evaluate(`renderNotifications([{id:'ui-auth-resolved',title:'UI verification: restored',body:'Temporary fixture',category:'agent',ts:new Date().toISOString(),read:true,authStatus:'resolved',action:{type:'auth-reconcile',kind:'mcp',serverId:'fixture'}}]);({resolved:document.querySelector('.notif-auth-resolved')?.textContent,buttons:document.querySelectorAll('[data-auth-reconcile]').length})`);assert.equal(resolved.buttons,0);assert(resolved.resolved.includes('Connection restored'));
 const permission=await evaluate(`renderNotifications([{id:'ui-human-preview',title:'Administrator permission needed',body:'Temporary rendering fixture',category:'agent',ts:new Date().toISOString(),requestStatus:'pending',action:{type:'human-request',app:'task-implementer',taskUrl:'https://github.com/example/tasks/issues/1',label:'Review request'}}]);({label:document.querySelector('[data-notif-open]')?.textContent,api:typeof window.robos.notifications.reviewHumanRequest})`);
 assert.equal(permission.label,'Review request');assert.equal(permission.api,'function');
 console.log('Live Dev Central renders reconnect actions and verified-recovery state. No notification fixtures persisted and no login started.');
 }finally{await evaluate(`(async()=>{renderNotifications(await window.robos.notifications.getNotifications());return true;})()`);}})().catch(e=>{console.error(e);process.exitCode=1;});
