'use strict';
window.openTaskRunnerLaunch=async function({mode,plan,refinement='',call,afterLaunch}){
 if(document.getElementById('runner-launch-dialog'))return;
 const dialog=document.createElement('dialog');dialog.id='runner-launch-dialog';dialog.innerHTML=`<header class="runner-heading"><div><span class="runner-eyebrow" data-launch-app>ROBOS AGENT TASK RUNNER</span><h2 id="runner-launch-title">Run task</h2></div><button type="button" data-dismiss aria-label="Close launch dialog" title="Close (Esc)">×</button></header><form hidden><p data-task></p><p data-purpose></p><div class="runner-settings"><robos-agent-selector></robos-agent-selector><label>Memory<select name="memoryGb"><option value="2">2 GiB</option><option value="4" selected>4 GiB</option><option value="8">8 GiB</option><option value="16">16 GiB</option></select></label><label>CPU cores<select name="cpus"><option>1</option><option selected>2</option><option>4</option><option>8</option></select></label></div><fieldset><legend>Repositories</legend><small>Selected repositories will be cloned into a fresh sandbox.</small><div data-repositories></div><div class="runner-add-repository"><input data-repository-url placeholder="organization/repository or GitHub URL" aria-label="Add repository URL"><button type="button" data-add-repository>Add</button></div><small data-repository-source></small></fieldset><fieldset><legend>MCP servers &amp; gateways</legend><small>Optional connections. Enable only the environments this agent needs. Login is shared across agents.</small><div data-mcp></div></fieldset><p class="runner-isolation">Temporary workspace · Changes preserved after the session · Review before merge</p><footer><span role="status" aria-live="polite">Loading launch settings…</span><button type="button" data-cancel>Cancel</button><button type="submit" data-launch>Launch agent</button></footer></form><p data-loading role="status">Loading task and sandbox settings…</p>`;dialog.setAttribute('aria-labelledby','runner-launch-title');
 dialog.querySelector('[data-launch-app]').textContent=mode==='plan'?'ROBOS TASK PLANNER · PLANNING AGENT':'ROBOS AGENT TASK RUNNER';document.body.append(dialog);dialog.showModal();const status=dialog.querySelector('footer [role=status]'),form=dialog.querySelector('form');dialog.onclose=()=>dialog.remove();dialog.querySelector('[data-dismiss]').onclick=()=>dialog.close();dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();
 try{const config=await call('launch-options',{mode,plan});if(!dialog.isConnected)return;form.hidden=false;form.querySelector('[data-task]').textContent=config.issue?.title?`#${config.issue.number} · ${config.issue.title}`:'';dialog.querySelector('[data-loading]').hidden=true;document.getElementById('runner-launch-title').textContent=mode==='implement'?'Implement task':'Plan task';form.querySelector('[data-purpose]').textContent=mode==='implement'?'Implement the reviewed plan and prepare a draft PR for human review.':'Inspect these repositories and draft an implementation plan. Stop for your review before coding.';
 const textOnly=config.textOnly===true;
 if(textOnly){dialog.querySelector('[data-launch-app]').textContent=config.appLabel||'ROBOS';dialog.querySelector('#runner-launch-title').textContent=config.title||'Generate';form.querySelector('[data-purpose]').textContent=config.purpose||'Choose an agent and model.';form.querySelectorAll('fieldset,.runner-isolation').forEach(e=>e.hidden=true);for(const name of ['memoryGb','cpus'])form.elements[name].closest('label').hidden=true;form.querySelector('.runner-settings').style.gridTemplateColumns='1fr';form.querySelector('[data-launch]').textContent=config.actionLabel||'Generate';}
 const selector=form.querySelector('robos-agent-selector');
 const mcpChoices=new Map();let mcpProvider=null;
 const renderMcp=()=>{const parent=form.querySelector('[data-mcp]');if(mcpProvider)mcpChoices.set(mcpProvider,[...parent.querySelectorAll('input:checked')].map(e=>e.value));mcpProvider=selector.value.provider;parent.replaceChildren();for(const s of config.mcpServers||[]){const row=document.createElement('div'),label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.value=s.id;box.dataset.mcpId=s.id;box.checked=(mcpChoices.get(mcpProvider)||config.mcpSelections?.[mcpProvider]||[]).includes(s.id);label.append(box,document.createTextNode(s.name+' · '+(s.environment||s.kind)));label.title=s.endpoint;const login=document.createElement('button');login.type='button';login.textContent='Sign in';login.title='Reuse saved MCP login or open Chrome once to authorize';login.onclick=async()=>{login.disabled=true;login.textContent='Connecting…';try{let result=await call('mcp-login',{serverId:s.id});login.textContent=result.authenticated?'Connected':'Login open in Chrome';while(result.loginPending&&dialog.isConnected){await new Promise(r=>setTimeout(r,2500));if(!dialog.isConnected)return;result=(await call('mcp-status',{provider:selector.value.provider})).find(item=>item.id===s.id)||{};}if(!dialog.isConnected)return;login.textContent=result.authenticated?'Connected':'Retry login';login.disabled=!!result.authenticated;if(result.error)status.textContent=result.error;}catch(e){status.textContent=e.message;login.textContent='Retry login';login.disabled=false;}};row.style.cssText='display:flex;justify-content:space-between;align-items:center;gap:12px;margin:8px 0';label.style.flexDirection='row';row.append(label,login);parent.append(row);}if(!parent.childElementCount)parent.textContent='No remote MCP connections imported.';};
 const available=config.availableRepositories||config.repositories||[];
 const selected=()=>[...form.querySelectorAll('[data-repositories] input:checked')].map(e=>e.value);
 const update=()=>{const count=selected().length;form.querySelector('[data-launch]').disabled=!config.available||!selector.ready||(!textOnly&&!count);status.textContent=config.error||selector.error||(textOnly?'Uses the selected provider’s credits only after you click Generate.':count?`${count} repositor${count===1?'y':'ies'} selected. Ready to launch.`:'Choose repositories from Git Projects below, or add a repository URL.');};
 const add=(url,checked)=>{const existing=[...form.querySelectorAll('[data-repositories] input')].find(e=>e.value.toLowerCase()===url.toLowerCase());if(existing){existing.checked=true;update();return;}const label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.value=url;box.checked=checked;box.onchange=update;const name=document.createElement('span');name.textContent=url.replace('https://github.com/','');label.title=url;label.append(box,name);form.querySelector('[data-repositories]').append(label);};
 for(const url of available)add(url,config.repositories.includes(url));
 form.querySelector('[data-repository-source]').textContent=config.repositorySource?`Selected from ${config.repositorySource.toLowerCase()}. Other registered repositories are optional.`:'No repositories are associated with this ticket yet. Registered Git Projects are available to select.';
 form.querySelector('[data-add-repository]').onclick=()=>{const input=form.querySelector('[data-repository-url]');try{let text=input.value.trim();if(/^[\w.-]+\/[\w.-]+$/.test(text))text='https://github.com/'+text;const url=new URL(text);if(url.protocol!=='https:'||url.hostname!=='github.com'||url.username||url.password||!/^\/[\w.-]+\/[\w.-]+(?:\.git)?\/?$/.test(url.pathname)||url.search||url.hash)throw Error('Enter a GitHub repository URL or organization/repository.');add(url.href.replace(/\.git\/?$/,'').replace(/\/$/,''),true);input.value='';update();}catch(e){status.textContent=e.message;}};
 form.querySelector('[data-repository-url]').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();form.querySelector('[data-add-repository]').click();}};
 selector.addEventListener('change',()=>{renderMcp();update();});await selector.load({providers:config.providers,provider:config.provider});renderMcp();update();
 form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('[data-launch]');if(button.disabled)return;button.disabled=true;button.textContent=textOnly?'Starting generation…':'Launching agent…';button.setAttribute('aria-busy','true');status.textContent=textOnly?'Starting generation…':'Launching the isolated agent session…';
 try{const launchConfig={...selector.value,mcpServers:[...form.querySelectorAll('[data-mcp-id]:checked')].map(e=>e.value),memoryGb:Number(form.elements.memoryGb.value),cpus:Number(form.elements.cpus.value),repositories:[...form.querySelectorAll('[data-repositories] input:checked')].map(e=>e.value)};await call('agent',{mode,plan,refinement,launchConfig});await afterLaunch?.();dialog.close();}catch(e){status.textContent=e.message;button.disabled=false;button.textContent=textOnly?(config.actionLabel||'Generate'):'Launch agent';button.setAttribute('aria-busy','false');}};
 }catch(e){dialog.querySelector('[data-loading]').textContent=e.message;}
};
document.addEventListener('DOMContentLoaded',()=>{const style=document.createElement('style');style.textContent=`
#runner-launch-dialog{color-scheme:dark;box-sizing:border-box;position:fixed;inset:0;margin:auto;width:min(740px,94vw);max-height:92vh;overflow:auto;background:#111820;color:#dbe5ee;border:1px solid #344354;border-radius:12px;padding:24px;box-shadow:0 24px 90px #0009;font:14px/1.5 system-ui,sans-serif}
#runner-launch-dialog [hidden]{display:none!important}#runner-launch-dialog *{box-sizing:border-box}#runner-launch-dialog::backdrop{background:#05090dbb;backdrop-filter:blur(3px)}
#runner-launch-dialog .runner-heading{display:flex;align-items:center;justify-content:space-between;gap:16px}#runner-launch-dialog .runner-eyebrow{font-size:10px;letter-spacing:1.6px;color:#8eabbc;font-weight:600}#runner-launch-dialog h2{font-size:23px;font-weight:600;margin:3px 0 0}#runner-launch-dialog [data-dismiss]{background:transparent;border:0;color:#aebac6;font-size:24px;padding:0 8px}
#runner-launch-dialog [data-task]{font-size:14px;font-weight:500;color:#dbe5ee;margin-bottom:4px}#runner-launch-dialog p{font-size:13px;line-height:1.6;margin:12px 0 20px;color:#aab9c7}#runner-launch-dialog .runner-settings{display:grid;grid-template-columns:1fr 1.5fr .7fr .7fr;gap:12px;margin:22px 0}
#runner-launch-dialog robos-agent-selector{grid-column:span 2}#runner-launch-dialog label{display:flex;flex-direction:column;gap:6px;font-size:12px;color:#b9c7d4}#runner-launch-dialog input:not([type=checkbox]),#runner-launch-dialog select{width:100%;min-width:0;margin:0;background:#0b1118;color:#e2eaf1;border:1px solid #354455;border-radius:6px;padding:9px 10px;font:13px system-ui}
#runner-launch-dialog :is(input,select,button):focus-visible{outline:2px solid #00bcd4;outline-offset:2px}#runner-launch-dialog button{padding:9px 14px;background:#1c2834;color:#d5e0e9;border:1px solid #3b4d5e;border-radius:6px;cursor:pointer;font:500 13px system-ui;white-space:nowrap}#runner-launch-dialog button:hover{background:#283949}#runner-launch-dialog [data-launch]{background:#00bcd4;color:#05252c;border-color:#00bcd4}#runner-launch-dialog button:disabled{opacity:.45;cursor:not-allowed}#runner-launch-dialog button[aria-busy=true]{cursor:wait}#runner-launch-dialog button[aria-busy=true]::before{content:"";display:inline-block;width:10px;height:10px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;margin-right:8px;animation:runner-spin .7s linear infinite}@keyframes runner-spin{to{transform:rotate(360deg)}}
#runner-launch-dialog fieldset{margin:0;padding:14px 0 0;border:0;border-top:1px solid #2c3a48;min-width:0}#runner-launch-dialog legend{padding:0 10px 0 0;font-weight:600;font-size:14px}#runner-launch-dialog small{display:block;font-size:12px;color:#8fa2b3;line-height:1.6}#runner-launch-dialog [data-repositories]{max-height:200px;overflow:auto;margin:10px 0;border:1px solid #2b3947;border-radius:6px}#runner-launch-dialog [data-repositories]:empty{display:none}#runner-launch-dialog [data-repositories] label{flex-direction:row;align-items:center;padding:9px 12px;gap:10px;font-size:13px;cursor:pointer;border-bottom:1px solid #263340}#runner-launch-dialog [data-repositories] label:last-child{border-bottom:0}#runner-launch-dialog [data-repositories] label:hover{background:#1c2935}#runner-launch-dialog [data-repositories] span{overflow-wrap:anywhere}#runner-launch-dialog input[type=checkbox]{accent-color:#00bcd4;width:15px;height:15px;flex-shrink:0}#runner-launch-dialog .runner-add-repository{display:flex;gap:8px;margin:12px 0}#runner-launch-dialog .runner-isolation{font-size:11px;color:#8297a9;margin:16px 0}
#runner-launch-dialog footer{display:flex;align-items:center;gap:10px;padding-top:16px;border-top:1px solid #2c3a48}#runner-launch-dialog footer [role=status]{flex:1;font-size:12px;color:#a3b7c7;margin-right:12px}
@media(max-width:600px){#runner-launch-dialog{padding:18px}#runner-launch-dialog .runner-settings{grid-template-columns:1fr 1fr}#runner-launch-dialog footer{flex-wrap:wrap;justify-content:flex-end}#runner-launch-dialog footer [role=status]{flex-basis:100%}}
`;document.head.append(style);});
