'use strict';
window.openTaskRunnerLaunch=options=>window.mountTaskRunnerLaunch(options);
window.mountTaskRunnerLaunch=async function({container,mode,plan,refinement='',call,afterLaunch,isReady=()=>true}){
 if(!container&&document.getElementById('runner-launch-dialog'))return;
 const embedded=!!container;const dialog=document.createElement(embedded?'section':'dialog');dialog.className='robos-runner-launch'+(embedded?' runner-embedded':'');if(!embedded)dialog.id='runner-launch-dialog';dialog.innerHTML=`<header class="runner-heading"><div><span class="runner-eyebrow" data-launch-app>ROBOS AGENT TASK RUNNER</span><h2 data-title>Run task</h2></div><button type="button" data-dismiss aria-label="Close launch dialog" title="Close (Esc)">×</button></header><form hidden><p data-task></p><p data-purpose></p><div class="runner-settings"><robos-agent-selector></robos-agent-selector></div><details data-repo-details><summary>Repositories <span data-repo-count></span></summary><fieldset><legend hidden>Repositories</legend><small>Selected repositories will be cloned into a fresh sandbox.</small><div data-repositories></div><div class="runner-add-repository"><input data-repository-url placeholder="organization/repository or GitHub URL" aria-label="Add repository URL"><button type="button" data-add-repository>Add</button></div><small data-repository-source></small></fieldset></details><details data-advanced><summary>Advanced <span data-resource-summary></span></summary><div class="runner-resources"><label>Memory<select name="memoryGb"><option value="2">2 GiB</option><option value="4" selected>4 GiB</option><option value="8">8 GiB</option><option value="16">16 GiB</option></select></label><label>CPU cores<select name="cpus"><option>1</option><option selected>2</option><option>4</option><option>8</option></select></label></div><fieldset><legend>MCP connections</legend><small>Optional connections. Enable only the environments this agent needs. Login is shared across agents.</small><div data-mcp></div></fieldset></details><footer><span role="status" aria-live="polite">Loading launch settings…</span><button type="button" data-cancel>Cancel</button><button type="submit" data-launch>Launch agent</button></footer></form><p data-loading role="status">Loading task and sandbox settings…</p>`;const titleId='runner-title-'+Math.random().toString(36).slice(2);dialog.querySelector('[data-title]').id=titleId;dialog.setAttribute('aria-labelledby',titleId);
 dialog.querySelector('[data-launch-app]').textContent=mode==='plan'?'ROBOS TASK PLANNER · PLANNING AGENT':'ROBOS AGENT TASK RUNNER';(container||document.body).append(dialog);if(!embedded)dialog.showModal();else{dialog.querySelector('header').hidden=true;dialog.querySelector('[data-cancel]').hidden=true;}const status=dialog.querySelector('footer [role=status]'),form=dialog.querySelector('form');dialog.onclose=()=>dialog.remove();dialog.querySelector('[data-dismiss]').onclick=()=>dialog.close();dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();let launching=false,launched=false;dialog.oncancel=e=>{if(launching)e.preventDefault();};
 try{const config=await call('launch-options',{mode,plan});if(!dialog.isConnected)return;form.hidden=false;form.querySelector('[data-task]').textContent=config.issue?.title?`#${config.issue.number} · ${config.issue.title}`:'';dialog.querySelector('[data-loading]').hidden=true;dialog.querySelector('[data-title]').textContent=mode==='implement'?'Implement task':'Plan task';form.querySelector('[data-purpose]').textContent=mode==='implement'?'Implement the reviewed plan and prepare a draft PR for human review.':'Inspect these repositories and draft an implementation plan. Stop for your review before coding.';
 if(config.title)dialog.querySelector('[data-title]').textContent=config.title;if(config.purpose)form.querySelector('[data-purpose]').textContent=config.purpose;if(config.actionLabel)form.querySelector('[data-launch]').textContent=config.actionLabel;
 if(config.hideRepositories)form.querySelector('[data-repo-details]').hidden=true;if(embedded){form.querySelector('[data-task]').hidden=true;form.querySelector('[data-purpose]').hidden=true;}
 const textOnly=config.textOnly===true;
 if(textOnly){dialog.querySelector('[data-launch-app]').textContent=config.appLabel||'ROBOS';dialog.querySelector('[data-title]').textContent=config.title||'Generate';form.querySelector('[data-purpose]').textContent=config.purpose||'Choose an agent and model.';form.querySelectorAll('details').forEach(e=>e.hidden=true);for(const name of ['memoryGb','cpus'])form.elements[name].closest('label').hidden=true;form.querySelector('.runner-settings').style.gridTemplateColumns='1fr';form.querySelector('[data-launch]').textContent=config.actionLabel||'Generate';}
 const selector=form.querySelector('robos-agent-selector');
 const mcpChoices=new Map();let mcpProvider=null;
 const renderMcp=()=>{const parent=form.querySelector('[data-mcp]');if(mcpProvider)mcpChoices.set(mcpProvider,[...parent.querySelectorAll('input:checked')].map(e=>e.value));mcpProvider=selector.value.provider;parent.replaceChildren();for(const s of config.mcpServers||[]){const row=document.createElement('div'),label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.value=s.id;box.dataset.mcpId=s.id;box.checked=(mcpChoices.get(mcpProvider)||config.mcpSelections?.[mcpProvider]||[]).includes(s.id);label.append(box,document.createTextNode(s.name+' · '+(s.environment||s.kind)));label.title=s.endpoint;const login=document.createElement('button');login.type='button';login.textContent='Sign in';login.title='Reuse saved MCP login or open Chrome once to authorize';login.onclick=async()=>{login.disabled=true;login.textContent='Connecting…';try{let result=await call('mcp-login',{serverId:s.id});login.textContent=result.authenticated?'Connected':'Login open in Chrome';while(result.loginPending&&dialog.isConnected){await new Promise(r=>setTimeout(r,2500));if(!dialog.isConnected)return;result=(await call('mcp-status',{provider:selector.value.provider})).find(item=>item.id===s.id)||{};}if(!dialog.isConnected)return;login.textContent=result.authenticated?'Connected':'Retry login';login.disabled=!!result.authenticated;if(result.error)status.textContent=result.error;}catch(e){status.textContent=e.message;login.textContent='Retry login';login.disabled=false;}};row.style.cssText='display:flex;justify-content:space-between;align-items:center;gap:12px;margin:8px 0';label.style.flexDirection='row';row.append(label,login);parent.append(row);}if(!parent.childElementCount)parent.textContent='No remote MCP connections imported.';};
 const available=config.availableRepositories||config.repositories||[];
 const selected=()=>[...form.querySelectorAll('[data-repositories] input:checked')].map(e=>e.value);
 const update=()=>{const count=selected().length;form.querySelector('[data-repo-count]').textContent='· '+count+' selected';form.querySelector('[data-resource-summary]').textContent='· '+form.elements.memoryGb.value+' GiB / '+form.elements.cpus.value+' CPUs';form.querySelector('[data-launch]').disabled=launching||launched||!isReady()||!config.available||!selector.ready||(!textOnly&&!count);if(launching||launched)return;status.textContent=config.error||selector.error||(textOnly?`Uses the selected provider’s credits only after you click ${config.actionLabel||'Generate'}.`:count?(isReady()?'Ready to launch.':'Describe the fix above to continue.'):'Choose repositories from Git Projects below, or add a repository URL.');};
 const add=(url,checked)=>{const existing=[...form.querySelectorAll('[data-repositories] input')].find(e=>e.value.toLowerCase()===url.toLowerCase());if(existing){existing.checked=true;update();return;}const label=document.createElement('label'),box=document.createElement('input');box.type='checkbox';box.value=url;box.checked=checked;box.onchange=update;const name=document.createElement('span');name.textContent=url.replace('https://github.com/','');label.title=url;label.append(box,name);form.querySelector('[data-repositories]').append(label);};
 for(const url of available)add(url,config.repositories.includes(url));
 form.querySelector('[data-repository-source]').textContent=config.repositorySource?`Selected from ${config.repositorySource.toLowerCase()}. Other registered repositories are optional.`:'No repositories are associated with this ticket yet. Registered Git Projects are available to select.';
 form.querySelector('[data-add-repository]').onclick=()=>{const input=form.querySelector('[data-repository-url]');try{let text=input.value.trim();if(/^[\w.-]+\/[\w.-]+$/.test(text))text='https://github.com/'+text;const url=new URL(text);if(url.protocol!=='https:'||url.hostname!=='github.com'||url.username||url.password||!/^\/[\w.-]+\/[\w.-]+(?:\.git)?\/?$/.test(url.pathname)||url.search||url.hash)throw Error('Enter a GitHub repository URL or organization/repository.');add(url.href.replace(/\.git\/?$/,'').replace(/\/$/,''),true);input.value='';update();}catch(e){status.textContent=e.message;}};
 form.querySelector('[data-repository-url]').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();form.querySelector('[data-add-repository]').click();}};
 for(const name of ['memoryGb','cpus']){if(config[name])form.elements[name].value=String(config[name]);form.elements[name].onchange=update;}if(!selected().length&&!textOnly&&!config.hideRepositories)form.querySelector('[data-repo-details]').open=true;selector.addEventListener('change',()=>{renderMcp();update();});await selector.load({providers:config.providers,provider:config.provider});renderMcp();update();
 form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('[data-launch]');if(button.disabled||launching||launched)return;launching=true;button.disabled=true;dialog.querySelectorAll('[data-dismiss],[data-cancel]').forEach(b=>b.disabled=true);button.textContent=textOnly?'Starting generation…':'Launching agent…';button.setAttribute('aria-busy','true');status.textContent=textOnly?'Starting generation…':'Launching the isolated agent session…';
 try{const launchConfig={...selector.value,mcpServers:[...form.querySelectorAll('[data-mcp-id]:checked')].map(e=>e.value),memoryGb:Number(form.elements.memoryGb.value),cpus:Number(form.elements.cpus.value),repositories:[...form.querySelectorAll('[data-repositories] input:checked')].map(e=>e.value)};await call('agent',{mode,plan,refinement,launchConfig});launched=true;await afterLaunch?.();if(embedded){form.querySelectorAll('input,select,button').forEach(e=>e.disabled=true);selector.setAttribute('disabled','');button.textContent='Launched';status.textContent='Session opened in Task Runner.';}else dialog.close();}catch(e){status.textContent=e.message;button.disabled=false;button.textContent=config.actionLabel||(textOnly?'Generate':'Launch agent');button.setAttribute('aria-busy','false');}finally{launching=false;button.setAttribute('aria-busy','false');dialog.querySelectorAll('[data-dismiss],[data-cancel]').forEach(b=>b.disabled=false);}};
 return {element:dialog,update,destroy:()=>dialog.remove()};
 }catch(e){dialog.querySelector('[data-loading]').textContent=e.message;}
};
document.addEventListener('DOMContentLoaded',()=>{const style=document.createElement('style');style.textContent=`
.robos-runner-launch{color-scheme:dark;box-sizing:border-box;color:#dbe5ee;font:13px/1.45 system-ui,sans-serif}
#runner-launch-dialog{position:fixed;inset:0;margin:auto;width:min(610px,94vw);max-height:88vh;overflow:auto;background:#111820;border:1px solid #344354;border-radius:8px;padding:18px;box-shadow:0 24px 90px #0009}
#runner-launch-dialog::backdrop{background:#05090dbb}
.robos-runner-launch [hidden]{display:none!important}.robos-runner-launch *{box-sizing:border-box}
.robos-runner-launch .runner-heading{display:flex;justify-content:space-between;align-items:center;gap:12px}.robos-runner-launch .runner-eyebrow{display:none}.robos-runner-launch h2{font-size:18px;margin:0}.robos-runner-launch [data-dismiss]{border:0;background:none;font-size:22px;padding:0 4px}
.robos-runner-launch [data-task]{font-weight:500;margin:8px 0 4px}.robos-runner-launch [data-purpose]{font-size:12px;color:#8fa2b3;margin:0 0 12px}
.robos-runner-launch .runner-settings{margin:12px 0}.robos-runner-launch label{display:flex;flex-direction:column;gap:5px;font-size:12px;color:#b9c7d4}.robos-runner-launch select,.robos-runner-launch input:not([type=checkbox]){width:100%;min-width:0;background:#0b1118;color:#e2eaf1;border:1px solid #354455;border-radius:4px;padding:7px 9px;font:13px system-ui}
.robos-runner-launch button{padding:7px 12px;background:#1c2834;color:#d5e0e9;border:1px solid #3b4d5e;border-radius:4px;cursor:pointer;font:500 13px system-ui;white-space:nowrap}
.robos-runner-launch button:disabled{opacity:.5;cursor:default}.robos-runner-launch :is(input,select,button):focus-visible{outline:2px solid #00bcd4;outline-offset:2px}.robos-runner-launch [data-launch],#inline-review-panel .robos-runner-launch [data-launch]{background:#00bcd4;color:#05252c;border-color:#00bcd4}
.robos-runner-launch button[aria-busy=true]::before{content:"";display:inline-block;width:10px;height:10px;border:2px solid currentColor;border-right-color:transparent;border-radius:50%;margin-right:8px;animation:runner-spin .7s linear infinite}@keyframes runner-spin{to{transform:rotate(360deg)}}
.robos-runner-launch details{border-top:1px solid #2c3a48;padding:9px 0}.robos-runner-launch summary{cursor:pointer;font-weight:500}.robos-runner-launch summary span{color:#8fa2b3;font-weight:400;font-size:12px}.robos-runner-launch fieldset{margin:10px 0 0;padding:0;border:0;min-width:0}.robos-runner-launch legend{font-size:12px;font-weight:500;margin-bottom:6px}.robos-runner-launch small{display:block;font-size:11px;color:#8fa2b3}.robos-runner-launch .runner-resources{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin:12px 0}
.robos-runner-launch [data-repositories]{max-height:160px;overflow:auto;margin:8px 0}.robos-runner-launch [data-repositories] label{flex-direction:row;align-items:center;padding:6px 0;gap:8px;cursor:pointer}.robos-runner-launch input[type=checkbox]{accent-color:#00bcd4}.robos-runner-launch .runner-add-repository{display:flex;gap:8px;margin:8px 0}
.robos-runner-launch footer{display:flex;align-items:center;gap:8px;padding-top:12px;border-top:1px solid #2c3a48}.robos-runner-launch footer [role=status]{flex:1;font-size:12px;color:#9fb8ca;white-space:normal}.runner-embedded{padding:0}.runner-embedded .runner-settings{margin:8px 0}.runner-embedded [data-loading]{margin:8px 0}
@media(max-width:500px){.robos-runner-launch footer{flex-wrap:wrap}.robos-runner-launch footer [role=status]{flex-basis:100%}}
`;document.head.append(style);});
