'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{spawn,execFile}=require('node:child_process'),{randomUUID}=require('node:crypto');
const core=require('../robos-agent-client/work-task/core');
const providers=require('./providers');
const github=require('./github-context');
const chatBridge=require('../team-chat-servers/lib/agent-bridge');
const DOCKER=()=>['-H',process.env.ROBOS_DOCKER_HOST||'unix:///var/run/docker.sock'];
function command(args,input){return new Promise((resolve,reject)=>{const p=spawn('docker',[...DOCKER(),...args],{stdio:['pipe','pipe','pipe']});let out='',err='';p.stdout.on('data',b=>out+=b);p.stderr.on('data',b=>err+=b);p.on('error',reject);p.on('close',c=>c?reject(Error(err||'Sandbox command failed')):resolve(out));p.stdin.on('error',()=>{});p.stdin.end(input);});}
function cli(bin,args){return new Promise((resolve,reject)=>execFile(bin,args,{encoding:'utf8',maxBuffer:4*1024*1024},(e,out)=>e?reject(e):resolve(out.trim())));}
const evidenceInstructions='Validation artifacts belong in ROBOS_EVIDENCE_DIR (/home/agent/evidence), outside every Git checkout. RobOS preserves this directory with the session before teardown. Store build/test logs, screenshots, videos and generated test reports there. Do not create or commit docs/validation, per-ticket audit documents, raw command output or other run artifacts in source repositories unless the user explicitly requests those as deliverables. Keep source changes, useful tests and intentional product documentation in the PR. Link directly to actual CI/check runs and evidence paths in the final response and PR description. Do not copy CI results into an LLM-written validation table, repeat a passed checklist, or author a narrative that certifies checks passed. The review UI reads original check links and preserved reports. For a relevant user-facing task, preserve a short real e2e/demo video demonstrating the completed behavior when recording is feasible, alongside the test runner HTML report in ROBOS_EVIDENCE_DIR. Use native runner reports, not an LLM recreation of their results. If no video exists or recording is not applicable, say so briefly and describe the testing strategy: what the relevant checks cover, what the reviewer should inspect, and remaining gaps. Do not fabricate videos, rerun unrelated suites solely to create a recording, or claim task completion from a green check alone. Never put secrets in evidence. Before committing, inspect the staged diff and unstage any accidentally staged run artifacts.';
async function exportRepos(id,dir){return new Promise((resolve,reject)=>{const source=spawn('docker',[...DOCKER(),'exec',id,'tar','-C','/home/agent','-cf','-','repos','evidence'],{stdio:['ignore','pipe','pipe']});const target=spawn('tar',['--no-same-owner','-C',dir,'-xf','-'],{stdio:['pipe','ignore','pipe']});source.stdout.pipe(target.stdin);let errors='',sourceCode,targetCode;const done=()=>{if(sourceCode===undefined||targetCode===undefined)return;if(sourceCode||targetCode)reject(Error(errors||'Repository export failed'));else resolve();};for(const p of [source,target]){p.on('error',reject);p.stderr.on('data',b=>errors+=b);}target.stdin.on('error',()=>{});source.on('close',c=>{sourceCode=c;done();});target.on('close',c=>{targetCode=c;done();});});}
async function options(url){const state=core.read(url);
 const metadata=await require('../task-planner/lib/issue-metadata').metadata(url);
 const repositoryOptions=await require('./repositories').resolve(url,metadata);
 const providerOptions=await providers.options();const provider=providerOptions.find(p=>p.id===state.launchConfig?.provider&&p.available)||providerOptions.find(p=>p.available)||providerOptions[0];
 let available=true,error='';try{await command(['image','inspect','robos-agent-task-runner:local']);}catch(e){available=false;error='Sandbox runtime unavailable. Build the RobOS Agent Task Runner image and start Docker.';}
 return {provider:provider.id,model:state.launchConfig?.provider===provider.id?state.launchConfig.model:provider.model,effort:state.launchConfig?.provider===provider.id?state.launchConfig.effort:'',providers:providerOptions,mcpServers:require('../robos-mcp-router/lib/connections').list(),mcpSelections:Object.fromEntries(providerOptions.map(p=>[p.id,require('../robos-mcp-router/lib/connections').preferences(p.id)])),...repositoryOptions,memoryGb:4,cpus:2,available,error,mode:require('../robos-agent-client/work-task/plan-approval').readiness(state).planReady?'implement':'plan',issue:metadata};
}
function validate(config){require('../robos-agent-client/reasoning-effort').args(config.provider,config.effort);if(!['codex','agy'].includes(config.provider))throw Error('Choose a task runner provider.');if(![2,4,8,16].includes(Number(config.memoryGb)))throw Error('Choose a supported session memory size.');if(![1,2,4,8].includes(Number(config.cpus)))throw Error('Choose a supported CPU count.');if(!Array.isArray(config.repositories)||!config.repositories.length)throw Error('Associate at least one Git repository with this ticket.');const repositories=[...new Set(config.repositories.map(require('../task-planner/lib/issue-metadata').repositoryUrl))];if(repositories.some(u=>!/^https:\/\/github\.com\/[\w.-]+\/[\w.-]+$/.test(u)))throw Error('This runner currently supports GitHub repositories.');if(config.model&&!/^[a-zA-Z0-9._:/-]{1,100}$/.test(config.model))throw Error('Invalid model name.');const mcpServers=[...new Set(config.mcpServers||[])];if(mcpServers.some(id=>!require('../robos-mcp-router/lib/connections').list().some(s=>s.id===id)))throw Error('Selected MCP connection is no longer imported.');return {...config,mcpServers,memoryGb:Number(config.memoryGb),cpus:Number(config.cpus),repositories};}
async function run(url,mode,prompt,onEvent,selectedConfig){const state=core.read(url),config=validate(selectedConfig||state.launchConfig),id='robos-task-'+randomUUID(),dir=path.join(core.folder(url),'sessions',id);await require('../robos-agent-client/reasoning-effort').validate(config);fs.mkdirSync(dir,{recursive:true});
 const notify=onEvent;onEvent=(role,text,name)=>{fs.appendFileSync(path.join(dir,'events.jsonl'),JSON.stringify({role,text,name,at:new Date().toISOString()})+'\n',{mode:0o600});notify(role,text,name);};
 let stopRequested=false;const earlyStop=()=>{stopRequested=true;};
 const binary=providers.binary(config.provider);
 const auth=providers.authentication(config.provider);
 const registryEnvironment=await require('../robos-lib/registry-credentials').resolve(config.repositories,cli);
 if(!path.isAbsolute(binary))throw Error('Configure an absolute provider executable path.');
 const update=patch=>core.save(url,{sandbox:{...core.read(url).sandbox,...patch,id,artifacts:dir}});
 update({status:'provisioning'});onEvent('system','Creating isolated Linux user, RAM-backed home, private process/network namespaces and virtual display.');
 let created=false,chat=null;
 process.once('SIGTERM',earlyStop);
 try{
 try{const network=JSON.parse(await command(['network','inspect','bridge']));const gateway=network[0]?.IPAM?.Config?.[0]?.Gateway;
 if(!gateway)throw Error('No local bridge');const remote=require('../robos-mcp-router/lib/remote-tools').bridge(config.mcpServers),slack=require('../team-chat-servers/lib/agent-chat').createService();chat=await chatBridge.start({host:gateway,call:(op,args)=>op?.startsWith('remote_')?remote(op,args):slack(op,args)});
 }catch{chat={error:'RobOS chat bridge is unavailable. A local Docker bridge network is required.',close:async()=>{}};onEvent('system',chat.error);}
 await command(['create','--name',id,'--label','robos.task='+url,'--read-only','--cap-drop=ALL','--security-opt=no-new-privileges','--security-opt=seccomp=unconfined','--security-opt=apparmor=unconfined','--security-opt=systempaths=unconfined','--pids-limit=512','--shm-size=512m','--memory',config.memoryGb+'g','--memory-swap',config.memoryGb+'g','--cpus',String(config.cpus),'--tmpfs',`/home/agent:rw,exec,uid=15000,gid=15000,mode=700,size=${config.memoryGb}g`,'--tmpfs','/tmp:rw,exec,mode=1777','--mount',`type=bind,src=${binary},dst=/opt/${config.provider},readonly`,...(config.provider==='codex'?['--mount',`type=bind,src=${path.join(path.dirname(binary),'codex-code-mode-host')},dst=/opt/codex-code-mode-host,readonly`]:[]),'robos-agent-task-runner:local','sleep','infinity']);created=true;await command(['start',id]);
 update({status:'preparing',memoryGb:config.memoryGb,cpus:config.cpus});
 const token=await cli('gh',['auth','token']);
 const bootstrap=`const fs=require('fs'),cp=require('child_process');let data='';process.stdin.on('data',b=>data+=b);process.stdin.on('end',()=>{const input=JSON.parse(data);fs.mkdirSync('/home/agent/.codex',{recursive:true});fs.mkdirSync('/home/agent/.gemini/antigravity-cli',{recursive:true});fs.writeFileSync(input.provider==='agy'?'/home/agent/.gemini/antigravity-cli/antigravity-oauth-token':'/home/agent/.codex/auth.json',JSON.stringify(input.auth),{mode:384});if(input.provider==='agy')fs.writeFileSync('/home/agent/.gemini/antigravity-cli/settings.json',JSON.stringify(input.agySettings),{mode:384});const githubContext=${github.githubContext.toString()};try{fs.writeFileSync('/home/agent/task-context.json',githubContext(input.url,input.token),{mode:384});}catch(e){console.error(e.message);process.exit(1);}fs.writeFileSync('/home/agent/prompt.txt',input.prompt,{mode:384});fs.writeFileSync('/home/agent/github-token',input.token,{mode:384});fs.writeFileSync('/home/agent/registry-env.json',JSON.stringify(input.registryEnvironment),{mode:384});fs.writeFileSync('/home/agent/robos-chat-bridge.json',JSON.stringify(input.chat),{mode:384});fs.writeFileSync('/home/agent/robos-chat.js',input.chatClient,{mode:384});fs.mkdirSync('/home/agent/evidence',{recursive:true});fs.mkdirSync('/home/agent/repos',{recursive:true});for(const url of input.repositories){const name=url.split('/').slice(-2).join('--');const header='AUTHORIZATION: basic '+Buffer.from('x-access-token:'+input.token).toString('base64');try{cp.execFileSync('git',['clone','--depth','1','--',url,'/home/agent/repos/'+name],{stdio:'ignore',env:{...process.env,GIT_CONFIG_COUNT:'1',GIT_CONFIG_KEY_0:'http.extraHeader',GIT_CONFIG_VALUE_0:header}});}catch{console.error('Unable to clone '+url+'. Check repository access.');process.exit(1);}const fix=input.reviewFix;if(fix&&url.toLowerCase().replace(/\\.git$/,'')===('https://github.com/'+fix.repo).toLowerCase()){const checkoutReviewFix=${require('./review-fix-checkout').checkoutReviewFix.toString()};checkoutReviewFix(cp,'/home/agent/repos/'+name,fix,{...process.env,GIT_CONFIG_COUNT:'1',GIT_CONFIG_KEY_0:'http.extraHeader',GIT_CONFIG_VALUE_0:header});}else{cp.execFileSync('git',['-C','/home/agent/repos/'+name,'checkout','-b',input.branch],{stdio:'ignore'});}}fs.writeFileSync('/home/agent/run.js',input.runner,{mode:384});});`;
 const branch=state.reviewFix?.branch||config.provider+'/robos-task-'+core.identity(url).number+'-'+Date.now();
 const runner=`const fs=require('fs'),cp=require('child_process');const repos=${JSON.stringify(config.repositories.map(url=>url.split('/').slice(-2).join('--')))};const env={...process.env,...JSON.parse(fs.readFileSync('/home/agent/registry-env.json','utf8')),ROBOS_EVIDENCE_DIR:'/home/agent/evidence',GH_TOKEN:fs.readFileSync('/home/agent/github-token','utf8'),NODE_AUTH_TOKEN:fs.readFileSync('/home/agent/github-token','utf8'),DISPLAY:':99'};cp.execFileSync('gh',['auth','setup-git'],{env,stdio:'ignore'});cp.execFileSync('git',['config','--global','user.name','RobOS Agent'],{env,stdio:'ignore'});cp.execFileSync('git',['config','--global','user.email','robos-agent@users.noreply.github.com'],{env,stdio:'ignore'});fs.mkdirSync('/tmp/.X11-unix',{recursive:true,mode:511});const display=cp.spawn('Xvfb',[':99','-screen','0','1920x1080x24','-nolisten','tcp'],{env,stdio:'ignore'});const args=${JSON.stringify(providers.args(config.provider,mode,config.model,config.effort))};if(${JSON.stringify(config.provider)}==='agy'){cp.execFileSync('/opt/agy',['mcp','add','robos_chat','node','/home/agent/robos-chat.js','--mcp'],{env,stdio:'ignore'});args.push('--print='+fs.readFileSync('/home/agent/prompt.txt','utf8'));}const agent=cp.spawn(${JSON.stringify('/opt/'+config.provider)},args,{cwd:'/home/agent/repos/'+repos[0],env,stdio:['pipe','inherit','inherit']});fs.writeFileSync('/home/agent/agent.pid',String(agent.pid));agent.stdin.end(fs.readFileSync('/home/agent/prompt.txt'));agent.on('error',e=>{console.error(e.message);process.exitCode=1;display.kill();});agent.on('exit',code=>{display.kill();process.exitCode=code||0;});`;
 await command(['exec','-i',id,'node','-e',bootstrap],JSON.stringify({url,reviewFix:state.reviewFix||null,chat:{url:chat.url,token:chat.token,error:chat.error,remoteMcp:config.mcpServers.length>0},chatClient:chatBridge.client,provider:config.provider,agySettings:providers.agySettings(mode),auth,token,registryEnvironment,repositories:config.repositories,prompt:require('../robos-agent-client/validation-policy').instructions+'\n\n'+evidenceInstructions+'\n\n'+github.instructions+'\n\n'+chatBridge.instructions+'\n\n'+prompt+'\nRepository clones are under /home/agent/repos. Use only these copies. GitHub Packages uses NODE_AUTH_TOKEN, already available in the environment; never print or persist credentials in repositories. Only if change-scoped validation needs a browser, Chromium system libraries are available; install the repository-matched browser with npx playwright install chromium (without --with-deps) only if missing. Localhost refers to this sandbox, not the developer desktop. Start services only for justified integration checks. Report missing services only when they block a relevant acceptance check; do not label inapplicable e2e as a failure or replace required real-stack validation with mocks. All work must be exported before sandbox teardown.',branch,runner}));
 if(stopRequested)throw Error('Stopped before agent launch.');
 update({status:'running',branch});if(state.workerPid)core.save(url,{phase:mode==='plan'?'planning-agent':'implementing'});onEvent('system','Sandbox ready. Starting '+(config.provider==='agy'?'AGY':'Codex')+' '+(config.model||'with its default model')+(config.effort?' · '+config.effort+' effort':'')+'.');
 const child=spawn('docker',[...DOCKER(),'exec',id,'node','/home/agent/run.js'],{stdio:['ignore','pipe','pipe']});
 let output='',pending='',agentError=null;const backend=require('../robos-agent-client/work-task/backend');
 const consume=line=>{if(!line.trim())return;try{const decoded=backend.decode(JSON.parse(line));for(const e of decoded.events)onEvent(e.role,e.text,e.name);if(decoded.text)output=decoded.text;if(decoded.error)agentError=decoded.error;}catch{onEvent('agent',line);}};
 child.stdout.on('data',b=>{pending+=b;const lines=pending.split('\n');pending=lines.pop();for(const line of lines)consume(line);});
 child.stderr.on('data',b=>onEvent('error',b.toString()));
 const stop=()=>{command(['exec',id,'node','-e',"const pid=Number(require('fs').readFileSync('/home/agent/agent.pid','utf8'));if(Number.isSafeInteger(pid)&&pid>1)process.kill(pid,'SIGTERM');"]).catch(()=>{});};process.once('SIGTERM',stop);
 let code;try{code=await new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});}finally{process.removeListener('SIGTERM',stop);}
 if(pending)consume(pending);
 update({status:'exporting'});onEvent('system','Exporting repository changes and session evidence before releasing sandbox memory.');await exportRepos(id,dir);update({status:'exported'});
 if(stopRequested)throw Error('Stopped by user. Repository copies were preserved.');if(agentError)throw Error(agentError);if(code===0&&!output.trim())throw Error('The agent ended without a final response. Check the session output. Repository copies were preserved.');if(code!==0)throw Error('Sandbox agent exited '+code+'. Repository copies were preserved.');return output;
 }finally{await chat?.close();process.removeListener('SIGTERM',earlyStop);if(created){const status=core.read(url).sandbox?.status;if(status==='exported'||status==='provisioning'||status==='preparing'){onEvent('system','Removing sandbox '+id+' and releasing its temporary home.');await command(['rm','-f',id]);update({status:'removed'});}else{update({status:'recovery-required'});onEvent('error','Sandbox retained as '+id+' because repository export did not finish. Preserve its work before removing it.');}}}
}
module.exports={options,validate,run,exportRepos,evidenceInstructions};
