'use strict';

const net = require('net');

/**
 * Hermetiq Buildbarn Helm chart repository URI.
 */
const BUILDBARN_OCI_CHART = 'oci://ghcr.io/hermetiq/buildbarn';

/**
 * Generates Kubernetes Helm values YAML for deploying Buildbarn RBE using Hermetiq's chart.
 * @param {Object} [options]
 * @returns {string} Helm values YAML content
 */
function generateBuildbarnHelmValues(options = {}) {
  const clusterName = options.clusterName || 'hermetiq-buildbarn-rbe';
  const replicaCount = options.replicaCount || 2;
  const storageCapacity = options.storageCapacity || '100Gi';
  const workerConcurrency = options.workerConcurrency || 8;
  const executionPort = options.executionPort || 8980;
  const casPort = options.casPort || 8981;

  return `# Hermetiq Buildbarn Helm Values
# Deployed from: ${BUILDBARN_OCI_CHART}
# Generated by RobOS Kgraph Parse Portal

global:
  clusterName: ${clusterName}
  environment: production

bbStorage:
  enabled: true
  replicas: ${replicaCount}
  service:
    port: ${casPort}
  persistence:
    enabled: true
    size: ${storageCapacity}
    storageClass: standard
  config:
    contentAddressableStorage:
      maximumSizeBytes: 107374182400 # 100 GiB
    actionCache:
      maximumSizeBytes: 10737418240  # 10 GiB

bbScheduler:
  enabled: true
  replicas: ${replicaCount}
  service:
    port: 8982
  config:
    workerPools:
      - name: linux-default
        concurrency: ${workerConcurrency}
        platform:
          properties:
            - name: OSFamily
              value: Linux
            - name: Arch
              value: x86_64

bbWorker:
  enabled: true
  replicas: ${replicaCount}
  resources:
    limits:
      cpu: "4000m"
      memory: "8Gi"
    requests:
      cpu: "1000m"
      memory: "2Gi"
  runner:
    type: docker
    socketPath: /var/run/docker.sock

bbFrontend:
  enabled: true
  replicas: ${replicaCount}
  service:
    type: ClusterIP
    port: ${executionPort}
  reapi:
    version: v2
`;
}

/**
 * Generates the Helm CLI command to install or upgrade Hermetiq's Buildbarn chart.
 * @param {Object} [options]
 * @returns {string} Helm CLI command string
 */
function generateHelmInstallCommand(options = {}) {
  const releaseName = options.releaseName || 'buildbarn';
  const namespace = options.namespace || 'buildbarn';
  const valuesFile = options.valuesFile || 'buildbarn-values.yaml';
  return `helm upgrade --install ${releaseName} ${BUILDBARN_OCI_CHART} --namespace ${namespace} --create-namespace -f ${valuesFile}`;
}

/**
 * Checks connectivity to an RBE cluster endpoint (TCP probe).
 * @param {string} endpoint Host:port or URL
 * @param {number} [timeoutMs=600]
 * @returns {Promise<Object>} { ok: boolean, status: string, endpoint: string }
 */
async function checkRbeClusterStatus(endpoint = '127.0.0.1:8980', timeoutMs = 600) {
  let host = '127.0.0.1';
  let port = 8980;

  try {
    const clean = endpoint.replace(/^[a-z]+:\/\//, '');
    const parts = clean.split(':');
    host = parts[0] || '127.0.0.1';
    port = parseInt(parts[1] || '8980', 10);
  } catch {}

  return new Promise((resolve) => {
    const socket = new net.Socket();
    socket.setTimeout(timeoutMs);

    socket.once('connect', () => {
      socket.destroy();
      resolve({
        ok: true,
        status: 'online',
        endpoint: `${host}:${port}`,
        protocol: 'REAPI_v2',
        provider: 'buildbarn',
        chart: BUILDBARN_OCI_CHART,
      });
    });

    socket.once('timeout', () => {
      socket.destroy();
      resolve({
        ok: false,
        status: 'unreachable',
        endpoint: `${host}:${port}`,
        protocol: 'REAPI_v2',
        provider: 'buildbarn',
        chart: BUILDBARN_OCI_CHART,
        note: 'Endpoint timed out; verify Hermetiq Buildbarn Helm deployment.',
      });
    });

    socket.once('error', (err) => {
      resolve({
        ok: false,
        status: 'offline',
        endpoint: `${host}:${port}`,
        protocol: 'REAPI_v2',
        provider: 'buildbarn',
        chart: BUILDBARN_OCI_CHART,
        error: err.message,
      });
    });

    socket.connect(port, host);
  });
}

/**
 * Generates a valid RobOS Knowledge Graph node for the RemoteExecutionCluster
 * conforming to W3C SHACL shape urn:robos:shape:RemoteExecutionClusterShape.
 * @param {Object} [options]
 * @returns {Object} SHACL-compliant JSON-LD node
 */
function generateKgraphClusterNode(options = {}) {
  const clusterId = options.clusterId || 'hermetiq-buildbarn-cluster';
  const title = options.title || 'Hermetiq Buildbarn REAPI v2 Cluster';
  const executionEndpoint = options.executionEndpoint || 'grpc://buildbarn-frontend.buildbarn.svc.cluster.local:8980';
  const casEndpoint = options.casEndpoint || 'grpc://buildbarn-storage.buildbarn.svc.cluster.local:8981';

  return {
    '@id': `urn:robos:cluster:${clusterId}`,
    '@type': [
      'robos:RemoteExecutionCluster',
      'robos:RemoteBuildCluster',
      'schema:ComputerPlatform',
    ],
    'dcterms:title': title,
    'dcterms:description': 'Distributed Remote Build Execution (RBE) cluster powered by Hermetiq Buildbarn Helm chart.',
    'robos:package': 'core-platform',
    'robos:protocol': 'REAPI_v2',
    'robos:provider': 'buildbarn',
    'robos:executionEndpoint': executionEndpoint,
    'robos:casEndpoint': casEndpoint,
    'robos:chart': BUILDBARN_OCI_CHART,
    'robos:schemaOrgType': 'https://schema.org/ComputerPlatform',
    'robos:domainStandard': 'https://github.com/bazelbuild/remote-apis',
    'robos:refersFrom': 'https://schema.org/ComputerPlatform',
  };
}

module.exports = {
  BUILDBARN_OCI_CHART,
  generateBuildbarnHelmValues,
  generateHelmInstallCommand,
  checkRbeClusterStatus,
  generateKgraphClusterNode,
};
