'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{execFileSync}=require('node:child_process');
const {chromium}=require('playwright-core');
function patch(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'robos-diff-'));const git=args=>execFileSync('git',args,{cwd:dir,encoding:'utf8'});git(['init','-q']);git(['config','user.name','Test']);git(['config','user.email','test@example.test']);fs.mkdirSync(path.join(dir,'src/core'),{recursive:true});fs.mkdirSync(path.join(dir,'src/ui'),{recursive:true});fs.writeFileSync(path.join(dir,'src/core/main.js'),'export function answer() {\n    return 41;\n}\n');fs.writeFileSync(path.join(dir,'src/ui/main.js'),'export const label = "Old";\n');fs.writeFileSync(path.join(dir,'old.txt'),'rename me\n');fs.writeFileSync(path.join(dir,'removed.txt'),'remove me\n');git(['add','.']);git(['commit','-qm','before']);const base=git(['rev-parse','HEAD']).trim();fs.writeFileSync(path.join(dir,'src/core/main.js'),'export function answer() {\n    return 42;\n}\n');fs.writeFileSync(path.join(dir,'src/ui/main.js'),'export const label = "<script>alert(1)</script>";\n');fs.renameSync(path.join(dir,'old.txt'),path.join(dir,'renamed.txt'));fs.unlinkSync(path.join(dir,'removed.txt'));fs.writeFileSync(path.join(dir,'image.bin'),Buffer.from([0,1,2,3]));git(['add','.']);git(['commit','-qm','after']);return git(['diff','--find-renames',base,'HEAD']);}
test('real git patch renders syntax, split layout, folder tree, status, and revision-scoped viewed marks',async()=>{
 const b=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome'});
 try{const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('http://127.0.0.1/',r=>r.fulfill({contentType:'text/html',body:'<section id="changes"></section>'}));await p.goto('http://127.0.0.1/');
 await p.addStyleTag({content:'body{margin:20px;background:#0d1117;color:#ddd;font:14px system-ui}#changes{display:flex;flex-direction:column;height:94vh}'});
 await p.addStyleTag({path:path.resolve(__dirname,'../../../pr-review/renderer/vendor/changes.css')});await p.addScriptTag({path:path.resolve(__dirname,'../../../pr-review/renderer/vendor/changes.js')});
 const raw=patch();await p.evaluate(raw=>{window.raw=raw;return window.mountChanges(document.getElementById('changes'),raw);},raw);
 await p.getByRole('treeitem',{name:/main.js/}).filter({has:p.locator('span')}).nth(0).click();
 assert.equal(await p.locator('.changes-filebar strong').innerText(),'src/core/main.js');
 assert.ok(await p.locator('.hljs-keyword').count()>0);assert.match(await p.locator('.changes-diff').innerText(),/return 42/);assert.ok(await p.locator('.d2h-code-linenumber').count()>0);
 assert.equal(await p.locator('.changes-diff script').count(),0);
 await p.getByRole('button',{name:'Split',exact:true}).click();assert.equal(await p.locator('.d2h-file-side-diff').count(),2);
 await p.getByRole('checkbox',{name:'Viewed',exact:true}).check();await p.getByRole('button',{name:'Collapse all'}).click();assert.equal(await p.locator('[data-file-path="src/core/main.js"]').isVisible(),false);
 await p.getByRole('button',{name:'Expand all'}).click();await p.getByRole('searchbox').fill('src/ui');assert.equal(await p.locator('[data-tree-node=file]').count(),1);await p.locator('[data-tree-node=file]').click();assert.equal(await p.locator('.changes-filebar strong').innerText(),'src/ui/main.js');assert.equal(await p.locator('.changes-diff script').count(),0);
 await p.getByRole('searchbox').fill('');await p.locator('[data-file-path="renamed.txt"]').click();assert.match(await p.locator('.changes-filebar').innerText(),/from old.txt/);await p.locator('[data-file-path="removed.txt"]').click();assert.match(await p.locator('.changes-filebar').innerText(),/D ·/);await p.locator('[data-file-path="image.bin"]').click();assert.match(await p.locator('.changes-diff').innerText(),/Binary/);
 await p.evaluate(()=>window.mountChanges(document.getElementById('changes'),window.raw));await p.locator('[data-file-path="src/core/main.js"]').click();assert.equal(await p.getByRole('checkbox',{name:'Viewed',exact:true}).isChecked(),true);
 await p.getByRole('button',{name:'Split',exact:true}).click();await p.screenshot({path:'/tmp/robos-changes-view.png'});
 await p.evaluate(()=>window.mountChanges(document.getElementById('changes'),window.raw.replace('return 42','return 43')));await p.locator('[data-file-path="src/core/main.js"]').click();assert.equal(await p.getByRole('checkbox',{name:'Viewed',exact:true}).isChecked(),false);
 const folder=p.locator('[data-folder="src"]');await folder.focus();await folder.press('ArrowLeft');assert.equal(await folder.getAttribute('aria-expanded'),'false');await folder.press('ArrowRight');assert.equal(await folder.getAttribute('aria-expanded'),'true');assert.deepEqual(errors,[]);
 }finally{await b.close();}
});
