'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {CIRecovery,recoveryPhase,recoveryPrompt}=require('../../../pr-review/lib/ci-recovery');
function fixture(){let head='failed-head',dirty='',ci={state:'failed',head,checks:[{name:'Buildkite',state:'failure',detailsUrl:'https://buildkite.com/org/pipeline/builds/1'}]};let pushes=0;
 const review={repo:'org/repo',workspace:os.tmpdir(),pullRequest:{number:1,url:'https://github.com/org/repo/pull/1'},demoAgent:{command:'/trusted/codex',args:['exec','--json','-c','sandbox_mode="workspace-write"']}};
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'ci-recovery-test-'));
 const recovery=new CIRecovery(review,{assertAuthor:async()=>({headBranch:'feature'}),push:async()=>{pushes++;}},dir,{providers:async()=>[{id:'codex',available:true,models:[{id:'test-model',reasoningEfforts:[{id:'high'}]}]}],readCI:async()=>ci,git:args=>args[0]==='branch'?'feature':args[0]==='status'?dirty:head,run:async()=>{head='fixed-head';return {reply:'Fixed and tested.',checkpointReached:true};}});
 return {recovery,setCI:value=>ci=value,setDirty:value=>dirty=value,setHead:value=>head=value,pushes:()=>pushes};
}
test('green requires the pushed revision and actual passing checks',()=>{assert.equal(recoveryPhase({pushedHead:'new'},{head:'old',state:'passed'},false,false),'waiting');assert.equal(recoveryPhase({pushedHead:'new'},{head:'new',state:'unknown'},false,false),'unknown');assert.equal(recoveryPhase({pushedHead:'new'},{head:'new',state:'passed'},false,false),'passed');});
test('fix is committed locally, review precedes push, and new CI failure stays failed',async()=>{const f=fixture();await f.recovery.start({model:'test-model',effort:'high'});await f.recovery.pending;assert.equal((await f.recovery.state()).phase,'ready');assert.equal(f.pushes(),0);assert.ok(f.recovery.session.agent.args.includes('sandbox_mode="workspace-write"'));await f.recovery.push();assert.equal(f.pushes(),1);assert.equal((await f.recovery.state()).phase,'waiting');f.setCI({head:'fixed-head',state:'failed',checks:[]});assert.equal((await f.recovery.state()).phase,'failed');});
test('dirty checkout and stale failed revision block launch',async()=>{const f=fixture();f.setDirty(' M file.js');await assert.rejects(()=>f.recovery.start(),/existing edits/);f.setDirty('');f.setHead('other-head');await assert.rejects(()=>f.recovery.start(),/differs/);});
test('agent errors and unsupported configuration never unlock push',async()=>{const f=fixture();f.recovery.run=async()=>{throw Error('Logs unavailable');};await f.recovery.start();await f.recovery.pending;assert.equal(f.recovery.session.status,'error');await assert.rejects(()=>f.recovery.push(),/no verified/);await assert.rejects(()=>f.recovery.start({model:'--bad value'}),/current RobOS catalog/);});
test('prompt requires actual logs, preserves tests and forbids automatic publishing',()=>{const f=fixture(),p=recoveryPrompt(f.recovery.review,{head:'a',checks:[]});assert.match(p,/actual failed job logs/);assert.match(p,/Never push/);assert.match(p,/weakening tests/);});

test('rejects unsupported agents and reasoning levels from outside the catalog',async()=>{const f=fixture();await assert.rejects(()=>f.recovery.start({provider:'agy'}),/supports Codex/);await assert.rejects(()=>f.recovery.start({model:'test-model',effort:'invented'}),/supported reasoning/);assert.equal(f.recovery.busy,false);});
