'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {ReviewActivity}=require('../../../pr-review/lib/review-activity'),{pingReview}=require('../../../pr-review/lib/review-ping');
function activity(){return new ReviewActivity('https://github.com/o/r/pull/1',path.join(fs.mkdtempSync(path.join(os.tmpdir(),'pr-activity-')),'activity.json'));}
test('waiting persists across reopening and resets for changed head, red CI, draft and closed PRs',()=>{const a=activity(),pr={state:'OPEN',isDraft:false,ciPassing:true,headRefOid:'a'};a.observe(pr,'2026-10-01T00:00:00Z');const b=new ReviewActivity(a.url,a.file);assert.equal(b.observe(pr).waiting.since,'2026-10-01T00:00:00Z');assert.equal(b.observe({...pr,headRefOid:'b'},'2026-10-02T00:00:00Z').waiting.since,'2026-10-02T00:00:00Z');for(const change of [{ciPassing:false},{isDraft:true},{state:'CLOSED'},{state:'MERGED'}]){b.observe(pr);assert.equal(b.observe({...pr,...change}).waiting,null);}});
test('ping validates choices, independently records delivery, and never repeats a request ID',async()=>{const a=activity(),calls=[];const state={assertAuthor:async()=>({author:'author',url:a.url}),options:async()=>({}),run:async(...args)=>calls.push(args)};const notification={send:async()=>{throw Error('offline');}};const input={github:true,message:{},reviewers:['reviewer'],requestId:'00000000-0000-4000-8000-000000000001'};await assert.rejects(pingReview({},state,notification,a),/Select/);await assert.rejects(pingReview({...input,reviewers:[]},state,notification,a),/reviewer/);const r=await pingReview(input,state,notification,a);assert.deepEqual(r.history.map(h=>h.status),['sent','unconfirmed']);assert.equal(calls.length,1);await pingReview(input,state,notification,a);assert.equal(calls.length,1);assert.equal(a.read().history.length,2);assert.ok(a.read().history.every(h=>h.at));});
test('message-only pings skip GitHub and draft PRs cannot be pinged',async()=>{const a=activity();const state={assertAuthor:async()=>({author:'author',url:a.url}),run:async()=>{throw Error('unexpected GitHub');}};const notification={send:async()=>({serverId:'slack',channel:'C1',reviewers:[]})};const input={message:{},requestId:'00000000-0000-4000-8000-000000000002'};assert.equal((await pingReview(input,state,notification,a)).history[0].status,'sent');state.assertAuthor=async()=>({isDraft:true});await assert.rejects(pingReview(input,state,notification,a),/Ready/);});
test('existing Slack notifications migrate once with their original timestamp',()=>{const a=activity(),config={readyNotification:{prUrl:a.url,status:'sent',requestId:'old-ping',ts:'1790942400.000001',serverId:'slack',channel:'C1'}};a.importNotifications(config);a.importNotifications(config);assert.equal(a.read().history.length,1);assert.equal(a.read().history[0].at,new Date(1790942400000).toISOString());});
test('saved ping timestamps acquire HTTPS conversation links without sending again',()=>{
 const a=activity(),receipt={prUrl:a.url,status:'sent',requestId:'existing',ts:'1790942400.000001',serverId:'slack',channel:'C1'};
 a.importNotifications({readyNotification:receipt});assert.equal(a.read().history[0].conversationUrl,null);
 a.importNotifications({readyNotification:receipt},[{id:'slack',provider:'slack',url:'https://hermetiq.slack.com'}]);
 assert.equal(a.read().history.length,1);assert.equal(a.read().history[0].conversationUrl,'https://hermetiq.slack.com/archives/C1/p1790942400000001?thread_ts=1790942400.000001&cid=C1');
 const {conversationLink}=require('../../../robos-lib/team-conversation-link');assert.equal(conversationLink({provider:'slack',url:'http://hermetiq.slack.com'},receipt),null);assert.equal(conversationLink({provider:'slack',url:'https://evil.example'},receipt),null);
});
