'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const {chromium}=require(process.env.ROBOS_PLAYWRIGHT_MODULE||'playwright-core');
test('live timer, previous ping, required delivery choice and GitHub-only request',async()=>{
 const b=await chromium.launch({headless:true});try{const p=await b.newPage();await p.route('http://localhost/',r=>r.fulfill({contentType:'text/html',body:'<div><button id="pr-ready-button">Ready</button></div>'}));await p.goto('http://localhost/');await p.evaluate(()=>{
 window.api={openUrl:async url=>{window.opened=url;},reviewActivity:async()=>({ok:true,pr:{isAuthor:true,state:'OPEN',isDraft:false,title:'Example',body:'Body'},waiting:{since:new Date(Date.now()-60000).toISOString()},history:[{kind:'message',status:'sent',at:'2026-10-01T12:00:00Z',channel:'C1',conversationUrl:'https://hermetiq.slack.com/archives/C1/p1790942400000001?thread_ts=1790942400.000001&cid=C1'}]}),reviewGitHubReviewers:async()=>({ok:true,reviewers:['alice']}),reviewMessageOptions:async()=>({ok:true,servers:[],settings:{}}),pingReview:async input=>{window.sent=input;return {ok:true,results:['GitHub reviews requested.'],history:[]}}};window.mountReviewerPicker=()=>({value:()=>[],validate(){},load:async()=>{}});
 });await p.addScriptTag({path:path.resolve(__dirname,'../../../pr-review/renderer/message-options.js')});await p.addScriptTag({path:path.resolve(__dirname,'../../../pr-review/renderer/review-activity.js')});await p.getByText(/Awaiting review/).waitFor();const before=await p.locator('.review-wait-timer').textContent();await p.waitForTimeout(1100);assert.notEqual(await p.locator('.review-wait-timer').textContent(),before);await p.getByRole('button',{name:'Ping for review',exact:true}).click();await p.getByText(/You last pinged/).waitFor();await p.getByRole('dialog').getByRole('link').click();assert.match(await p.evaluate(()=>window.opened),/^https:\/\/hermetiq.slack.com\/archives\/C1\/p/);assert.equal(await p.getByRole('textbox',{name:'GitHub reviewers'}).inputValue(),'alice');await p.getByRole('checkbox',{name:'Request GitHub reviews'}).uncheck();await p.getByRole('dialog').getByRole('button',{name:'Ping for review'}).click();await p.getByText('Select GitHub reviews or a team message.').waitFor();assert.equal(await p.evaluate(()=>window.sent),undefined);await p.getByRole('checkbox',{name:'Request GitHub reviews'}).check();await p.getByRole('dialog').getByRole('button',{name:'Ping for review'}).click();await p.getByText('GitHub reviews requested.').waitFor();assert.equal((await p.evaluate(()=>window.sent)).github,true);await p.getByRole('button',{name:'Done'}).click();assert.equal(await p.getByRole('dialog').count(),0);
 }finally{await b.close();}
});
