'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');const {chromium}=require(process.env.ROBOS_PLAYWRIGHT_MODULE||'playwright-core');
test('saved review highlights failed CI, supports search and opens its saved session',async()=>{
 const b=await chromium.launch({headless:true});try{const p=await b.newPage();await p.setContent('<input id="global-search"><section id="saved-code-reviews"></section>');await p.evaluate(()=>{window.opened=[];window.robos={savedReviews:async()=>({ok:true,data:[{id:'filters',title:'Compact filters',repo:'Hermetiq/cloud-native',taskTitle:'Onboarding',taskUrl:'https://github.com/Hermetiq/tasks/issues/98',pr:{number:484,url:'https://github.com/Hermetiq/cloud-native/pull/484'},ci:{state:'failed',checks:[{state:'failure',name:'Buildkite'}]}}]}),openCodeReview:async id=>{opened.push(id);return {ok:true}},openUrl:async url=>opened.push(url)};});
 await p.addScriptTag({path:path.resolve(__dirname,'../../../dev-central/renderer/task-reviews.js')});await p.getByText('CI checks failed',{exact:true}).waitFor();await p.getByRole('button',{name:'Open Code Review'}).click();await p.getByText('Code Review opened.').waitFor();assert.deepEqual(await p.evaluate(()=>opened),['filters']);await p.locator('input').fill('missing');assert.equal(await p.locator('article').isVisible(),false);await p.locator('input').fill('#484');assert.equal(await p.locator('article').isVisible(),true);await p.getByRole('button',{name:'View CI checks'}).click();assert.equal((await p.evaluate(()=>opened)).at(-1),'https://github.com/Hermetiq/cloud-native/pull/484/checks');
 }finally{await b.close();}
});
test('Code Review failure banner refreshes to unavailable without retaining a false pass',async()=>{
 const b=await chromium.launch({headless:true});try{const p=await b.newPage();await p.setContent('<header class="theater-topbar"><div class="theater-actions"></div></header>');await p.evaluate(()=>{window.api={reviewCIStatus:async()=>({state:'failed',checks:[{state:'failure',name:'Buildkite'}],url:'https://github.com/org/repo/pull/1'}),openUrl:async()=>{}};});await p.addScriptTag({path:path.resolve(__dirname,'../../../pr-review/renderer/ci-status.js')});await p.getByText('CI checks failed',{exact:true}).waitFor();assert.equal(await p.locator('.review-live-ci').getAttribute('data-state'),'failed');await p.evaluate(()=>window.api.reviewCIStatus=async()=>({state:'unknown',checks:[],error:'Unable to refresh CI status from GitHub.'}));await p.getByRole('button',{name:'Refresh CI'}).click();await p.getByText('CI status unavailable',{exact:true}).waitFor();assert.equal(await p.getByRole('button',{name:'View checks'}).count(),0);
 }finally{await b.close();}
});
