'use strict';
const $=id=>document.getElementById(id);const collapsed=new Set();let data={servers:[],channels:[],providers:{}},editing=null,serverId=null,kind='server',generation=0,editRoot='',editRevision='';
async function call(name,input={}){const r=await window.chat[name]({root:$('graph').value,...input});if(!r.ok)throw Error(r.error);return r.data;}
const action=(label,title,fn)=>{const b=document.createElement('button');b.textContent=label;b.title=title;b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){$('status').textContent=e.message;}finally{b.disabled=false;}};return b;};
function render(){const query=$('search').value.toLowerCase();$('entries').replaceChildren();let count=0;for(const s of data.servers){const channels=data.channels.filter(c=>c['robos:chatServer']?.['@id']===s['@id']);if(![s,...channels].some(n=>(n['dcterms:title']+' '+(data.providers[n['robos:provider']]||'')).toLowerCase().includes(query)))continue;count++;row(s,false);if(!collapsed.has(s['@id']))channels.forEach(n=>row(n,true));}$('empty').hidden=count>0;$('empty').textContent=data.servers.length?'No matching servers.':'No chat servers in this KGraph. Add your first server.';}
function row(n,channel){const tr=document.createElement('tr');tr.className=channel?'channel':'';const name=document.createElement('td');name.textContent=(channel?'↳ ':'')+n['dcterms:title'];name.title=n['dcterms:description']||n['dcterms:title'];if(!channel&&data.channels.some(c=>c['robos:chatServer']?.['@id']===n['@id'])){const toggle=action(collapsed.has(n['@id'])?'▸':'▾','Show or hide channels',()=>{collapsed.has(n['@id'])?collapsed.delete(n['@id']):collapsed.add(n['@id']);render();});toggle.setAttribute('aria-expanded',String(!collapsed.has(n['@id'])));name.prepend(toggle);}tr.append(name);const provider=document.createElement('td');provider.textContent=channel?n['robos:channelId']:data.providers[n['robos:provider']]||n['robos:provider'];tr.append(provider);const time=document.createElement('td');time.textContent=n['robos:updatedAt']?new Date(n['robos:updatedAt']).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—';tr.append(time);const actions=document.createElement('td');if(n['robos:url'])actions.append(action('Open','Open this workspace or channel in your browser',()=>call('open',{id:n['@id']})));if(!channel&&n['robos:provider']==='slack')actions.append(action('Test','Verify the password-store credential belongs to this Slack workspace',async()=>{$('status').textContent='Checking Slack connection…';const result=await call('test',{id:n['@id']});$('status').textContent='Connected to '+result.workspace+' as '+result.user+' · Workspace '+result.workspaceId;}));if(!channel&&n['robos:provider']==='slack')actions.append(action('Reconnect','Reauthorize Slack and replace its saved OAuth token',()=>openReconnect(n['@id'])));actions.append(action('Edit','Edit this KGraph entry',()=>edit(n,channel?'channel':'server')));if(!channel)actions.append(action('Add channel','Add a channel, Zulip stream or Matrix room reference',()=>edit(null,'channel',n['@id'])));actions.append(action('Remove','Remove this configuration from RobOS',async()=>{await call('remove',{id:n['@id'],revision:data.revision});await refresh();}));tr.append(actions);$('entries').append(tr);}
async function refresh(){const ticket=++generation;$('add').disabled=true;if(!$('graph').value){data={servers:[],channels:[],providers:{}};$('entries').replaceChildren();$('empty').hidden=false;$('empty').textContent='Select a KGraph to manage team chat servers.';return;}try{const next=await call('list');if(ticket!==generation)return;data=next;data.servers.sort((a,b)=>(b['robos:updatedAt']||'').localeCompare(a['robos:updatedAt']||''));$('provider').replaceChildren(...Object.entries(data.providers).map(([id,label])=>new Option(label,id)));render();$('status').textContent='';$('add').disabled=false;}catch(e){if(ticket===generation)$('status').textContent=e.message;}}
function edit(n,type,parent){kind=type;editing=n?.['@id']||null;serverId=parent||n?.['robos:chatServer']?.['@id'];editRoot=$('graph').value;editRevision=data.revision;$('form-title').textContent=(n?'Edit ':'Add ')+(kind==='channel'?'channel':'server');$('name').value=n?.['dcterms:title']||'';$('description').value=n?.['dcterms:description']||'';$('url').value=n?.['robos:url']||'';$('url').required=kind==='server';$('provider').value=n?.['robos:provider']||'slack';$('workspace').value=n?.['robos:workspaceId']||'';$('credential').value=n?.['robos:credentialRef']||'';$('channel').value=n?.['robos:channelId']||'';$('channel').required=kind==='channel';for(const id of ['provider-field','workspace-field','credential-field'])$(id).hidden=kind==='channel';$('channel-field').hidden=kind!=='channel';$('form-status').textContent='';$('editor').showModal();$('name').focus();}
$('add').onclick=()=>edit(null,'server');$('search').oninput=render;$('refresh').onclick=refresh;$('graph').addEventListener('change',refresh);for(const id of ['cancel','close'])$(id).onclick=()=>$('editor').close();$('editor').onclick=e=>{if(e.target===$('editor')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}};
$('form').onsubmit=async e=>{e.preventDefault();$('save').disabled=true;$('save').textContent='Saving…';try{await call('save',{root:editRoot,revision:editRevision,id:editing,kind,serverId,name:$('name').value,description:$('description').value,provider:$('provider').value,url:$('url').value,workspaceId:$('workspace').value,credentialRef:$('credential').value,channelId:$('channel').value});$('editor').close();await refresh();$('status').textContent='Saved to KGraph.';}catch(e){$('form-status').textContent=e.message;}finally{$('save').disabled=false;$('save').textContent='Save to KGraph';}};
refresh();

let reconnectId='',reconnectRoot='';
async function openReconnect(id){let server=data.servers.find(s=>s['@id']===id);if(!server){for(const graph of await window.robosKGraphs.list()){const r=await window.chat.list({root:graph.id});if(r.ok&&r.data.servers.some(s=>s['@id']===id)){await $('graph').load(graph.id);await refresh();server=data.servers.find(s=>s['@id']===id);break;}}}if(!server)return;reconnectId=id;reconnectRoot=$('graph').value;$('reconnect-name').textContent=server['dcterms:title'];$('replacement-token').value='';$('reconnect-status').textContent='';if(!$('reconnect').open)$('reconnect').showModal();}
$('slack-settings').onclick=()=>call('auth-settings');$('cancel-reconnect').onclick=()=>$('reconnect').close();$('reconnect').addEventListener('close',()=>{$('replacement-token').value='';});
$('reconnect-form').onsubmit=async e=>{e.preventDefault();$('save-reconnect').disabled=true;$('reconnect-status').textContent='Verifying workspace and updating password store…';try{await call('reconnect',{root:reconnectRoot,id:reconnectId,token:$('replacement-token').value});$('reconnect').close();$('status').textContent='Slack reconnected. Agents can retry their blocked operation.';}catch(e){$('reconnect-status').textContent=e.message;}finally{$('replacement-token').value='';$('save-reconnect').disabled=false;}};
window.chatRecovery.onRequest(openReconnect);window.chatRecovery.target().then(id=>{if(id)openReconnect(id);});
