'use strict';
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('robos', {
  launchApp:      (appId) => ipcRenderer.invoke('launch-app', appId),
  getRunningApps: ()      => ipcRenderer.invoke('get-running-apps'),
  getPinnedApps:  ()      => ipcRenderer.invoke('get-pinned-apps'),
  setPinnedApps:  (list)  => ipcRenderer.invoke('set-pinned-apps', list),
  getAppMeta:     ()      => ipcRenderer.invoke('get-app-meta'),
  getX11Windows:  ()      => ipcRenderer.invoke('get-x11-windows'),
  focusWindow:    (wid)   => ipcRenderer.invoke('focus-window', wid),
  minimizeWindow: (wid)   => ipcRenderer.invoke('minimize-window', wid),
  maximizeWindow: (wid)   => ipcRenderer.invoke('maximize-window', wid),
  unmaximizeWindow:(wid)  => ipcRenderer.invoke('unmaximize-window', wid),
  restoreWindow:  (wid)   => ipcRenderer.invoke('restore-window', wid),
  closeWindow:    (wid)   => ipcRenderer.invoke('close-window', wid),
  toggleShowDesktop: ()   => ipcRenderer.invoke('toggle-show-desktop'),
  getActiveWindow:()      => ipcRenderer.invoke('get-active-window'),
  execDesktopAction: (execStr) => ipcRenderer.invoke('exec-desktop-action', execStr),
  switchToGnome:  ()      => ipcRenderer.invoke('switch-to-gnome'),
  setDockZone:    (h)     => ipcRenderer.invoke('set-dock-zone', h),
  setDockRect:    (r)     => ipcRenderer.invoke('set-dock-rect', r),
  setDragLock:    (v)     => ipcRenderer.invoke('set-drag-lock', v),
  setMenuOpen:    (v)     => ipcRenderer.sendSync('set-menu-open-sync', v),
  debugLog:       (msg)   => ipcRenderer.send('debug-log', msg),
  setMockWindows: (list)  => ipcRenderer.invoke('set-mock-windows', list),
  getTestHistory: ()      => ipcRenderer.invoke('get-test-history'),
  resetTestHistory: ()    => ipcRenderer.invoke('reset-test-history'),
  listAgentProfiles: ()   => ipcRenderer.invoke('list-agent-profiles'),
  killAgentProfile: (u)   => ipcRenderer.invoke('kill-agent-profile', u),
  wipeAllAgentProfiles:() => ipcRenderer.invoke('wipe-all-agent-profiles'),
});
