'use strict';
const cp=require('node:child_process'),{promisify}=require('node:util'),crypto=require('node:crypto');
const {Client}=require('@modelcontextprotocol/sdk/client/index.js');
const {StreamableHTTPClientTransport}=require('@modelcontextprotocol/sdk/client/streamableHttp.js');
const {key,endpoint}=require('./connections');
const passVault={
 async read(id){const fs=require('node:fs'),path=require('node:path'),os=require('node:os');if(!fs.existsSync(path.join(process.env.PASSWORD_STORE_DIR||path.join(os.homedir(),'.password-store'),'robos/mcp',id+'.gpg')))return {};try{return JSON.parse((await promisify(cp.execFile)('pass',['show','robos/mcp/'+id],{encoding:'utf8',timeout:30000})).stdout);}catch(e){throw Error('Unlock the password store to use MCP authentication.');}},
 async write(id,value){await new Promise((resolve,reject)=>{const p=cp.spawn('pass',['insert','--force','--multiline','robos/mcp/'+id],{stdio:['pipe','ignore','ignore']});const timer=setTimeout(()=>{p.kill('SIGTERM');reject(Error('Unlock the password store and retry MCP login.'));},35000);p.on('error',()=>{clearTimeout(timer);reject(Error('Password store unavailable.'));});p.on('close',c=>{clearTimeout(timer);c?reject(Error('Unable to save MCP login in the password store.')):resolve();});p.stdin.on('error',()=>{});p.stdin.end(JSON.stringify(value));});}
};
function chrome(url){return new Promise((resolve,reject)=>{const bin=process.platform==='darwin'?'open':'google-chrome';const args=process.platform==='darwin'?['-a','Google Chrome',url]:[url];const p=cp.spawn(bin,args,{detached:true,stdio:'ignore'});p.on('error',()=>reject(Error('Google Chrome could not open. Install Chrome and retry login.')));p.on('spawn',()=>{p.unref();resolve();});});}
function createManager({vault=passVault,openBrowser=chrome,notify=()=>{},redirectBase='http://127.0.0.1:19196',makeClient=()=>new Client({name:'RobOS',version:'1.0.0'}),makeTransport=(url,opts)=>new StreamableHTTPClientTransport(url,opts),now=Date.now}={}){
 const entries=new Map();
 function entry(server){const id=key(server);if(!entries.has(id))entries.set(id,{server,id,loaded:false,secret:{},status:'disconnected',pending:null,busy:null,client:null});return entries.get(id);}
 async function load(e){if(!e.loaded){e.secret=await vault.read(e.id);e.loaded=true;}}
 async function save(e){await vault.write(e.id,e.secret);}
 function provider(e){return {
  get redirectUrl(){return redirectBase+'/oauth/callback/'+e.id;},
  get clientMetadata(){return {client_name:'RobOS',redirect_uris:[this.redirectUrl],grant_types:['authorization_code','refresh_token'],response_types:['code'],token_endpoint_auth_method:'none',scope:'openid email profile offline_access'};},
  state:()=>{if(!e.pending)throw Error('MCP login required');return e.pending.state;},
  clientInformation:()=>e.secret.client,
  saveClientInformation:async value=>{e.secret.client=value;await save(e);},
  tokens:()=>e.secret.tokens,
  saveTokens:async value=>{e.secret.tokens={...value,...(!value.refresh_token&&e.secret.tokens?.refresh_token?{refresh_token:e.secret.tokens.refresh_token}:{})};e.secret.expiresAt=value.expires_in?now()+value.expires_in*1000:null;await save(e);},
  saveCodeVerifier:value=>{e.verifier=value;},codeVerifier:()=>e.verifier,
  redirectToAuthorization:async url=>{if(!e.pending)throw Error('MCP login required');if(e.pending.opened)return;await openBrowser(url.toString());e.pending.opened=true;e.lastBrowserOpenedAt=now();e.status='login-pending';},
  invalidateCredentials:async scope=>{if(scope==='all')e.secret={};else if(scope==='tokens')delete e.secret.tokens;else if(scope==='client')delete e.secret.client;await save(e);}
 };}
 function status(server){const e=entry(server);if(e.pending&&e.pending.until<now()){e.pending=null;e.status='login-required';e.error='Login timed out. Retry sign-in from RobOS Agents.';}return {status:e.status,authenticated:e.status==='connected',loginPending:!!e.pending,lastBrowserOpenedAt:e.lastBrowserOpenedAt||null,error:e.error||null};}
 async function connect(e){await load(e);if(e.client)return e.client;const transport=makeTransport(new URL(endpoint(e.server.endpoint)),{authProvider:e.server.authType==='none'?undefined:provider(e),reconnectionOptions:{maxRetries:0,maxReconnectionDelay:1000,initialReconnectionDelay:1000,reconnectionDelayGrowFactor:1},fetch:(url,init)=>fetch(url,{...init,redirect:'error',signal:init?.signal?AbortSignal.any([init.signal,AbortSignal.timeout(30000)]):AbortSignal.timeout(30000)})});e.transport=transport;const client=makeClient();try{await client.connect(transport);e.client=client;e.status='connected';e.error=null;e.pending=null;return client;}catch(err){await client.close().catch(()=>{});e.client=null;if(e.pending?.opened){e.status='login-pending';return null;}const auth=/unauthorized|login required|invalid_grant|401|invalid_token/i.test(err.message);e.status=auth?'login-required':'error';e.error=auth?'MCP login required. Open RobOS Agents to reconnect.':'MCP connection failed. Check the endpoint, permissions and password store.';if(auth)notify(e.server,e.id+':'+crypto.createHash('sha256').update(e.secret.tokens?.access_token||'no-token').digest('hex'));throw Error(e.error);}}
 async function serial(e,fn){if(e.busy)return e.busy;e.busy=fn().finally(()=>{e.busy=null;});return e.busy;}
 async function login(server){const e=entry(server);status(server);if(e.pending)return status(server);if(e.client)return status(server);if(e.busy){await e.busy.catch(()=>{});if(e.client||e.pending)return status(server);}e.pending={state:crypto.randomBytes(32).toString('hex'),until:now()+5*60*1000,opened:false};try{await serial(e,()=>connect(e));}catch(err){e.pending=null;throw err;}return status(server);}
 async function callback(id,state,code,error){const e=entries.get(id);if(!e?.pending||e.pending.exchanging||e.pending.until<now()||state!==e.pending.state)throw Error('Invalid or expired login callback.');if(error||!code){e.pending=null;e.status='login-required';e.error='Login was not approved. Retry from RobOS Agents.';throw Error(e.error);}e.pending.exchanging=true;try{await e.transport.finishAuth(code);e.pending=null;await connect(e);return status(e.server);}catch{e.pending=null;e.status='login-required';e.error='MCP login could not be completed. Retry from RobOS Agents.';throw Error(e.error);}}
 async function client(server){const e=entry(server);status(server);if(e.pending)throw Error('MCP login is already open in Chrome. Complete it before retrying.');if(e.status==='login-required')throw Error(e.error||'MCP login required. Open RobOS Agents to reconnect.');return serial(e,()=>connect(e));}
 async function perform(server,method,args){const c=await client(server);try{if(method==='tools/list')return await c.listTools(args);if(method==='tools/call')return await c.callTool(args);if(method==='resources/list')return await c.listResources(args);if(method==='resources/read')return await c.readResource(args);if(method==='prompts/list')return await c.listPrompts(args);if(method==='prompts/get')return await c.getPrompt(args);throw Error('Unsupported remote MCP operation.');}catch(err){if(/unauthorized|login required|invalid_grant|401|invalid_token/i.test(err.message)){const e=entry(server);e.status='login-required';e.error='MCP login required. Open RobOS Agents to reconnect.';await e.client?.close().catch(()=>{});e.client=null;notify(server,e.id+':'+crypto.createHash('sha256').update(e.secret.tokens?.access_token||'no-token').digest('hex'));throw Error(e.error);}throw Error('Remote MCP request failed. The operation was not retried.');}}
 async function invoke(server,method,args){const e=entry(server);const run=()=>perform(server,method,args);const result=(e.requestQueue||Promise.resolve()).then(run,run);e.requestQueue=result.catch(()=>{});return result;}
 return {status,login,callback,invoke};
}
module.exports={createManager,chrome};
