'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');const {createManager}=require('./oauth'),{key}=require('./connections');
const server={id:'dev',name:'Development',endpoint:'https://mcp.example.test/mcp',authType:'oauth'};
function fixture(options={}){let opens=0,reads=0,writes=0,notifications=0,loginUrl='',stored={};const manager=createManager({now:options.now,vault:{read:async()=>{reads++;return structuredClone(stored);},write:async(id,v)=>{writes++;stored=structuredClone(v);}},openBrowser:async url=>{if(options.browserFailure)throw Error('Chrome unavailable');opens++;loginUrl=url;},notify:()=>notifications++,makeTransport:(url,{authProvider:p})=>({p,finishAuth:async code=>{assert.equal(code,'approved-code');await p.saveTokens({access_token:'test-access',token_type:'Bearer'});}}),makeClient:()=>({connect:async t=>{if(!await t.p.tokens()){await t.p.saveCodeVerifier('test-verifier');await t.p.redirectToAuthorization(new URL('https://login.example.test/authorize?state='+await t.p.state()));throw Error('Unauthorized');}},close:async()=>{},listTools:async()=>({tools:[]})})});return {manager,counts:()=>({opens,reads,writes,notifications}),state:()=>new URL(loginUrl).searchParams.get('state')};}
test('catalog/status never logs in; simultaneous explicit logins open one browser and validate callback state',async()=>{const f=fixture(),m=f.manager;assert.equal(m.status(server).authenticated,false);assert.equal(f.counts().reads,0);await Promise.all([m.login(server),m.login(server),m.login(server)]);assert.equal(f.counts().opens,1);assert.equal(m.status(server).loginPending,true);await assert.rejects(m.callback(key(server),'wrong','approved-code'),/Invalid/);assert.equal(f.counts().writes,0);await m.callback(key(server),f.state(),'approved-code');assert.equal(m.status(server).authenticated,true);await m.login(server);assert.equal(f.counts().opens,1);assert.deepEqual(await m.invoke(server,'tools/list',{}),{tools:[]});});
test('background unauthenticated calls notify once and never open Chrome',async()=>{const f=fixture();for(let i=0;i<4;i++)await assert.rejects(f.manager.invoke(server,'tools/list',{}),/login required/);assert.equal(f.counts().opens,0);assert.equal(f.counts().notifications,1);});
test('denied login stays disconnected and requires an explicit retry',async()=>{const f=fixture();await f.manager.login(server);await assert.rejects(f.manager.callback(key(server),f.state(),null,'access_denied'),/not approved/);await assert.rejects(f.manager.invoke(server,'tools/list',{}),/not approved/);assert.equal(f.counts().opens,1);await f.manager.login(server);assert.equal(f.counts().opens,2);});
test('requests to one connection serialize token refresh instead of racing it',async()=>{let active=0,maxActive=0;const manager=createManager({vault:{read:async()=>({tokens:{access_token:'fixture',token_type:'Bearer'}})},makeTransport:()=>({}),makeClient:()=>({connect:async()=>{},listTools:async()=>{active++;maxActive=Math.max(maxActive,active);await new Promise(r=>setTimeout(r,10));active--;return {tools:[]};}})});await Promise.all([manager.invoke(server,'tools/list',{}),manager.invoke(server,'tools/list',{}),manager.invoke(server,'tools/list',{})]);assert.equal(maxActive,1);});
test('failed browser launch and expired login cannot leave a permanent waiting state',async()=>{const failed=fixture({browserFailure:true});await assert.rejects(failed.manager.login(server));assert.equal(failed.manager.status(server).loginPending,false);let now=1;const timed=fixture({now:()=>now});await timed.manager.login(server);now+=301000;assert.equal(timed.manager.status(server).loginPending,false);assert.match(timed.manager.status(server).error,/timed out/);assert.equal(timed.counts().opens,1);});
