'use strict';
async function openFeaturePicker(){
 document.getElementById('feature-picker')?.remove();const dialog=document.createElement('dialog');dialog.id='feature-picker';
 dialog.innerHTML='<h2>Assign features to myself</h2><p>Choose one or more features. Your current assignments stay in place.</p><input id="feature-search" placeholder="Search title, issue number, or repository" aria-label="Search features"><div id="feature-options"></div><p id="feature-picker-status" role="status"></p><footer><button id="feature-picker-cancel">Cancel</button><button id="feature-picker-save" disabled>Assign selected (0)</button></footer>';
 document.body.append(dialog);dialog.showModal();const status=dialog.querySelector('#feature-picker-status'),selected=new Set();let choices=[],busy=false;
 const button=dialog.querySelector('#feature-picker-save');function count(){button.textContent=`Assign selected (${selected.size})`;button.disabled=busy||!selected.size;}
 function render(){const query=dialog.querySelector('#feature-search').value.toLowerCase();const list=dialog.querySelector('#feature-options');list.replaceChildren();for(const f of choices.filter(f=>!f.closed&&(f.code+' '+f.name+' '+f.id).toLowerCase().includes(query))){const row=document.createElement('label');row.title=f.description;const box=document.createElement('input');box.type='checkbox';box.checked=selected.has(f.id);box.disabled=f.assigned||busy;box.onchange=()=>{if(box.checked)selected.add(f.id);else selected.delete(f.id);count();};const title=document.createElement('span');title.textContent=`${f.code} ${f.name}`;const note=document.createElement('small');note.textContent=f.assigned?'Already assigned to you':f.id.split('/').slice(3,5).join('/');row.append(box,title,note);list.append(row);}if(!list.children.length)list.textContent='No matching open features.';}
 dialog.querySelector('#feature-search').oninput=render;dialog.querySelector('#feature-picker-cancel').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});
 button.onclick=async()=>{busy=true;count();render();status.textContent='Assigning on GitHub…';try{for(const id of [...selected]){const r=await window.robos.setActiveFeature(id);if(!r.ok)throw Error(r.error);selected.delete(id);renderFeatures(r.features,r.activeFeature);choices=r.features;}dialog.close();updateKPIRibbon();}catch(e){status.textContent=e.message;}finally{busy=false;count();render();}};
 status.textContent='Loading features…';try{const result=await window.robos.getFeatures();if(!result.ok)throw Error(result.error);choices=result.data;status.textContent='';render();}catch(e){status.textContent=e.message;}
}
