extends Node2D
## Draws whatever the ScenarioEngine is running: any party, any monsters, any
## positions. Used in "prove it to a human" mode so every scenario gets a video.
## The Infinity AI's player inputs are shown as virtual-cursor clicks.

const MAP_RECT := Rect2(60, 180, 1520, 860)
const LOG_RECT := Rect2(1604, 190, 300, 850)
const PARTY_COLOR := Color(0.25, 0.7, 1.0)
const ENEMY_COLOR := Color(1.0, 0.35, 0.3)
const MAX_TOKEN := 56.0

## Token diameter in pixels: one 5-ft cell, so neighbouring creatures never overlap
var TOKEN := 56.0

var scale_px := 8.0
var origin := Vector2.ZERO
var textures := {}
var fx: Array = []
var log_label: RichTextLabel
var header: Label
var banner: Label
var font: Font

func _ready() -> void:
	font = ThemeDB.fallback_font
	var bg := ColorRect.new()
	bg.color = Color(0.05, 0.06, 0.09)
	bg.size = Vector2(1920, 1080)
	bg.z_index = -10
	add_child(bg)
	header = Label.new()
	header.position = Vector2(60, 132)
	header.add_theme_font_size_override("font_size", 26)
	header.add_theme_color_override("font_color", Color(0.85, 0.95, 1.0))
	add_child(header)
	var panel := Panel.new()
	panel.position = LOG_RECT.position
	panel.size = LOG_RECT.size
	var sb := StyleBoxFlat.new()
	sb.bg_color = Color(0.03, 0.04, 0.07, 0.92)
	sb.border_color = Color(0.2, 0.35, 0.5)
	sb.set_border_width_all(1)
	sb.set_corner_radius_all(8)
	panel.add_theme_stylebox_override("panel", sb)
	add_child(panel)
	log_label = RichTextLabel.new()
	log_label.bbcode_enabled = true
	log_label.scroll_following = true
	log_label.position = LOG_RECT.position + Vector2(10, 8)
	log_label.size = LOG_RECT.size - Vector2(20, 16)
	log_label.add_theme_font_size_override("normal_font_size", 13)
	add_child(log_label)
	banner = Label.new()
	banner.visible = false
	banner.position = Vector2(MAP_RECT.position.x, MAP_RECT.position.y + MAP_RECT.size.y / 2 - 60)
	banner.size = Vector2(MAP_RECT.size.x, 120)
	banner.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	banner.add_theme_font_size_override("font_size", 72)
	add_child(banner)
	ScenarioEngine.event_recorded.connect(_on_event)
	ScenarioEngine.scenario_loaded.connect(func(_s): rebuild())
	rebuild()

func rebuild() -> void:
	fx.clear()
	if log_label:
		log_label.clear()
	if banner:
		banner.visible = false
	_fit_view()
	for ev in ScenarioEngine.events:
		_log(ev)
	queue_redraw()

func _fit_view() -> void:
	var lo := Vector2(INF, INF)
	var hi := Vector2(-INF, -INF)
	for id in ScenarioEngine.actors:
		var p: Vector2 = ScenarioEngine.actors[id]["pos"]
		lo = Vector2(min(lo.x, p.x), min(lo.y, p.y))
		hi = Vector2(max(hi.x, p.x), max(hi.y, p.y))
	if lo.x == INF:
		lo = Vector2.ZERO
		hi = Vector2(80, 60)
	if ScenarioEngine.map_size != Vector2.ZERO:
		lo = Vector2(min(lo.x, 0.0), min(lo.y, 0.0))
		hi = Vector2(max(hi.x, ScenarioEngine.map_size.x), max(hi.y, ScenarioEngine.map_size.y))
	lo -= Vector2(25, 25)
	hi += Vector2(25, 25)
	var span := hi - lo
	span = Vector2(max(span.x, 90.0), max(span.y, 55.0))
	scale_px = min(MAP_RECT.size.x / span.x, MAP_RECT.size.y / span.y)
	TOKEN = clampf(5.0 * scale_px * 0.92, 24.0, MAX_TOKEN)
	origin = MAP_RECT.position + (MAP_RECT.size - span * scale_px) / 2.0 - lo * scale_px

func to_screen(feet: Vector2) -> Vector2:
	return origin + feet * scale_px

## A creature at (x, y) stands in the 5-ft cell whose corner is (x, y): draw it in the cell's middle
func cell_screen(feet: Vector2) -> Vector2:
	return to_screen(feet + Vector2(2.5, 2.5))

func _tex(path: String) -> Texture2D:
	if textures.has(path):
		return textures[path]
	var t: Texture2D = load(path) if ResourceLoader.exists(path) else null
	if t == null and path.ends_with(".png") and FileAccess.file_exists(path):
		# Blockout images are generated by robos-crpg-blockout and may not be imported yet
		var img := Image.load_from_file(ProjectSettings.globalize_path(path))
		if img:
			t = ImageTexture.create_from_image(img)
	textures[path] = t
	return t

func _process(delta: float) -> void:
	for f in fx:
		f["t"] -= delta
	fx = fx.filter(func(f): return f["t"] > 0)
	queue_redraw()

func _draw() -> void:
	draw_rect(MAP_RECT, Color(0.08, 0.1, 0.14))
	# 5-ft grid
	var step := 5.0 * scale_px
	if step >= 6.0:
		var x := fmod(origin.x - MAP_RECT.position.x, step) + MAP_RECT.position.x
		while x < MAP_RECT.end.x:
			draw_line(Vector2(x, MAP_RECT.position.y), Vector2(x, MAP_RECT.end.y), Color(1, 1, 1, 0.04))
			x += step
		var y := fmod(origin.y - MAP_RECT.position.y, step) + MAP_RECT.position.y
		while y < MAP_RECT.end.y:
			draw_line(Vector2(MAP_RECT.position.x, y), Vector2(MAP_RECT.end.x, y), Color(1, 1, 1, 0.04))
			y += step
	# Blockout background: the scene's static layer (floor, walls, buildings, props)
	var bg_path := str(ScenarioEngine.map_info.get("background", ""))
	if bg_path != "" and ScenarioEngine.map_size != Vector2.ZERO:
		var bg := _tex(bg_path)
		if bg:
			draw_texture_rect(bg, Rect2(to_screen(Vector2.ZERO), ScenarioEngine.map_size * scale_px), false)
	draw_rect(MAP_RECT, Color(0.25, 0.4, 0.55, 0.6), false, 2.0)
	# Traps
	for tid in ScenarioEngine.traps:
		var tr: Dictionary = ScenarioEngine.traps[tid]
		var p := cell_screen(tr["pos"])
		var col := Color(0.6, 0.6, 0.6, 0.5) if tr["disarmed"] else (Color(1, 0.8, 0.2, 0.9) if tr["detected"] else Color(1, 0.8, 0.2, 0.25))
		draw_rect(Rect2(p - Vector2(12, 12), Vector2(24, 24)), col, false, 2.0)
		draw_string(font, p + Vector2(-14, 28), tid, HORIZONTAL_ALIGNMENT_LEFT, -1, 11, col)
	# Area / arrow effects under tokens
	for f in fx:
		var a: float = clamp(f["t"] / f["life"], 0.0, 1.0)
		match f["kind"]:
			"circle":
				draw_circle(f["at"], f["r"], Color(f["color"], 0.18 * a))
				draw_arc(f["at"], f["r"], 0, TAU, 64, Color(f["color"], 0.8 * a), 3.0)
			"arrow":
				draw_line(f["from"], f["to"], Color(f["color"], 0.9 * a), 4.0)
				draw_circle(f["to"], 8.0, Color(f["color"], 0.9 * a))
	# Tokens
	for id in ScenarioEngine.actors:
		_draw_actor(ScenarioEngine.actors[id], id == ScenarioEngine.current_actor)
	header.text = "%s   ·   Round %d   ·   seed %d   ·   %s" % [str(ScenarioEngine.scenario.get("name", "")), ScenarioEngine.round_num, Dice.seed_value, ScenarioEngine.status if ScenarioEngine.outcome == "" else ScenarioEngine.outcome.to_upper()]

func _draw_actor(a: Dictionary, is_current: bool) -> void:
	var p := cell_screen(a["pos"])
	var side_col := PARTY_COLOR if a["side"] == "party" else ENEMY_COLOR
	var down := ScenarioEngine.is_down(a)
	if is_current:
		draw_circle(p, TOKEN * 0.72, Color(1, 0.9, 0.3, 0.25))
	draw_circle(p, TOKEN * 0.55, Color(0.02, 0.02, 0.04))
	var tex := _tex(str(a["portrait"]))
	if tex:
		var mod := Color(0.35, 0.35, 0.35) if down else Color.WHITE
		draw_texture_rect(tex, Rect2(p - Vector2(TOKEN, TOKEN) / 2.0, Vector2(TOKEN, TOKEN)), false, mod)
	draw_arc(p, TOKEN * 0.55, 0, TAU, 48, side_col if not down else Color(0.4, 0.4, 0.4), 3.0)
	if a["dead"]:
		draw_line(p - Vector2(18, 18), p + Vector2(18, 18), Color(0.9, 0.2, 0.2), 4.0)
		draw_line(p + Vector2(-18, 18), p + Vector2(18, -18), Color(0.9, 0.2, 0.2), 4.0)
	# HP bar
	var w := TOKEN + 16
	var frac: float = clamp(float(a["hp"]) / max(1.0, float(a["max_hp"])), 0.0, 1.0)
	var bar := Rect2(p + Vector2(-w / 2, TOKEN * 0.62), Vector2(w, 7))
	draw_rect(bar, Color(0.15, 0.05, 0.05))
	draw_rect(Rect2(bar.position, Vector2(w * frac, 7)), Color(0.2, 0.85, 0.35) if frac > 0.5 else (Color(0.95, 0.75, 0.2) if frac > 0.25 else Color(0.95, 0.25, 0.2)))
	var label := "%s  %d/%d" % [a["name"], int(a["hp"]), int(a["max_hp"])]
	draw_string(font, p + Vector2(-w / 2 - 20, TOKEN * 0.62 + 22), label, HORIZONTAL_ALIGNMENT_CENTER, w + 40, 12, Color(0.9, 0.93, 1.0))
	var conds: Array = a["conditions"].keys()
	if not conds.is_empty():
		draw_string(font, p + Vector2(-w / 2 - 30, -TOKEN * 0.62 - 6), ", ".join(conds), HORIZONTAL_ALIGNMENT_CENTER, w + 60, 11, Color(1, 0.8, 0.4))

func _on_event(ev: Dictionary) -> void:
	_log(ev)
	var t := str(ev["type"])
	match t:
		"player_input":
			var actor: Dictionary = ScenarioEngine.actors.get(str(ev["actor"]), {})
			var input: Dictionary = ev["input"]
			var at := Vector2.ZERO
			if input.has("point"):
				at = cell_screen(Vector2(float(input["point"][0]), float(input["point"][1])))
			elif input.has("target") and ScenarioEngine.actors.has(str(input["target"])):
				at = cell_screen(ScenarioEngine.actors[str(input["target"])]["pos"])
			elif input.has("to"):
				at = cell_screen(Vector2(float(input["to"][0]), float(input["to"][1])))
			elif not actor.is_empty():
				at = cell_screen(actor["pos"])
			if not actor.is_empty():
				fx.append({"kind": "arrow", "from": cell_screen(actor["pos"]), "to": at, "color": PARTY_COLOR if actor["side"] == "party" else ENEMY_COLOR, "t": 0.9, "life": 0.9})
			if has_node("/root/QAOverlay") and at != Vector2.ZERO:
				get_node("/root/QAOverlay").human_move_and_click(at, Color(0.1, 0.95, 0.4, 0.95) if str(ev["source"]) != "script" else Color(1, 0.8, 0.2, 0.95), ScenarioEngine._describe_input(input))
		"area_resolved":
			var spell: Dictionary = ScenarioEngine.content["spells"].get(str(ev["spell"]), {})
			var area: Dictionary = spell.get("mechanics", {}).get("area", {})
			fx.append({"kind": "circle", "at": cell_screen(Vector2(float(ev["point"][0]), float(ev["point"][1]))), "r": float(area.get("size", 20)) * scale_px, "color": Color(1, 0.5, 0.15), "t": 1.2, "life": 1.2})
		"damage":
			var tgt: Dictionary = ScenarioEngine.actors.get(str(ev["target"]), {})
			if not tgt.is_empty():
				FloatingTextManagerSingleton.spawn_damage(cell_screen(tgt["pos"]) - Vector2(0, 40), int(ev["adjusted"]), bool(ev["crit"]), str(ev["damage_type"]), self)
		"heal":
			var h: Dictionary = ScenarioEngine.actors.get(str(ev["target"]), {})
			if not h.is_empty():
				FloatingTextManagerSingleton.spawn_heal(cell_screen(h["pos"]) - Vector2(0, 40), int(ev["hp_after"]) - int(ev["hp_before"]), self)
		"attack":
			if not bool(ev["hit"]):
				var m: Dictionary = ScenarioEngine.actors.get(str(ev["target"]), {})
				if not m.is_empty():
					FloatingTextManagerSingleton.spawn_miss(cell_screen(m["pos"]) - Vector2(0, 40), self)
		"scenario_ended":
			banner.text = str(ev["outcome"]).to_upper()
			banner.add_theme_color_override("font_color", Color(0.3, 1, 0.5) if ev["outcome"] == "victory" else Color(1, 0.35, 0.3))
			banner.visible = true

func _log(ev: Dictionary) -> void:
	if log_label == null or not ev.has("text"):
		return
	var col := "#cbd5e1"
	match str(ev["type"]):
		"player_input":
			col = "#7dd3fc"
		"damage", "died":
			col = "#fca5a5"
		"heal":
			col = "#86efac"
		"round_started", "scenario_ended":
			col = "#fde68a"
		"condition_applied", "condition_removed":
			col = "#fdba74"
	log_label.append_text("[color=%s]%s[/color]\n" % [col, str(ev["text"]).replace("[", "(").replace("]", ")")])
