apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default "acme-petshop-local" }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name }}
