'use strict';
document.addEventListener('DOMContentLoaded',()=>{
 const more=document.getElementById('planner-more');
 document.addEventListener('keydown',event=>{if(event.key==='Escape'&&more.open){more.open=false;more.querySelector('summary').focus();event.preventDefault();}});
 document.addEventListener('pointerdown',event=>{if(!more.contains(event.target))more.open=false;});
 document.addEventListener('focusin',event=>{if(!more.contains(event.target))more.open=false;});
 more.addEventListener('click',event=>{if(event.target.closest('button'))more.open=false;});
 const toolbar=document.createElement('div');toolbar.id='feature-toolbar';toolbar.setAttribute('role','toolbar');toolbar.setAttribute('aria-label','Feature actions');
 document.getElementById('planner-navigation').after(toolbar);
 toolbar.append(document.getElementById('planner-edit'),document.getElementById('planner-save'));
 const ai=document.createElement('button');ai.className='btn btn-outline';ai.id='planner-ai-revise';ai.textContent='Revise with AI';ai.onclick=revisePlannerMarkdown;toolbar.append(ai);
 const actions=document.getElementById('planner-more-actions');
 for(const id of ['planner-import','planner-add-task','planner-secondary','planner-templates'])actions.append(document.getElementById(id));
 toolbar.append(more,document.getElementById('planner-primary'));
 const help=document.createElement('p');help.id='planner-action-help';toolbar.after(help);
 document.querySelector('.planner-plan-tools').hidden=true;
 document.querySelector('.planner-context-actions').hidden=true;
 const field=document.querySelector('.planner-product-field');document.getElementById('planner-panel-details').prepend(field);
 const membership=document.createElement('div');membership.id='planner-membership';field.prepend(membership);
 document.querySelector('[data-planner-tab=details]').textContent='Project';
 document.getElementById('btn-new-project').hidden=true;
 document.querySelector('.sidebar-header').append(document.getElementById('btn-workspace-plans'));
 document.getElementById('btn-workspace-plans').className='btn btn-outline';
 document.getElementById('planner-project-search').placeholder='Filter projects, features, epics and tasks';
 const original=window.refreshPlannerUX;
 window.refreshPlannerUX=function(...args){original(...args);const record=selectedPlannerRecord(),isProject=record?.kind==='project';
  document.getElementById('project-metadata-card').hidden=!isProject;document.getElementById('epic-parent-section').hidden=true;
  const group=plannerProducts(projectsList).find(p=>p.families.some(f=>f.project.id===currentProjectId||f.children.some(c=>c.id===currentProjectId)));
  membership.replaceChildren();const title=document.createElement('h3');title.textContent=group?.name||'(No Project)';const description=document.createElement('p');const project=projectsList.find(p=>p.kind==='project'&&(p.id===group?.id||p.name===group?.name));description.textContent=project?.description||(group?.id==='unassigned'?'This work item is not in a project. Choose a project to organize it with related work.':'Organize features, epics, and tasks within this project.');membership.append(title,description);
  for(const id of ['btn-generate','work-task-approve','work-task-implement','work-task-source']){const b=document.getElementById(id);if(b)b.hidden=true;}
  const primary=document.getElementById('planner-primary');
  if(plannerSession&&!plannerSession.plan&&!plannerSession.workerPid)primary.textContent='Draft implementation plan';
  if(!plannerSession&&!isProject&&record?.kind==='epic')primary.textContent='Draft tasks from requirements';
  help.textContent=plannerSession&&!plannerSession.plan?'Choose agent and sandbox settings, then draft implementation steps in isolated repository clones. Save the implementation plan before starting coding. Signoff is needed only when explicitly required.':plannerSession?.planReady?'Run the saved implementation plan in Task Implementer.':plannerSession?.plan?'Review the implementation steps, revise if needed, then obtain the required signoff.':isProject?'Open a feature or add work to this project.':'Draft a list of tasks from these requirements, then review them before creating tickets.';
  ai.hidden=isProject||!record;primary.hidden=!record;
  document.querySelector('[data-planner-tab=details]').textContent=isProject?'Project settings':'Project';
 };
 window.refreshPlannerUX(plannerSession);
});
