'use strict';
window.attachPeoplePicker=function(host,{selected,onChange}){
 host.innerHTML='<label for="signoff-person-search">Required reviewer</label><input id="signoff-person-search" type="search" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-controls="signoff-person-results" autocomplete="off" placeholder="Search by name or email"><div id="signoff-person-results" role="listbox" hidden></div><small class="people-picker-status" role="status">Type a name or email to find a reviewer.</small>';
 const input=host.querySelector('input'),list=host.querySelector('[role=listbox]'),status=host.querySelector('[role=status]');let timer,version=0,items=[],active=-1,chosen=selected;
 const close=()=>{list.hidden=true;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');active=-1;};
 const label=p=>p.displayName+(p.email?' · '+p.email:'');
 function choose(p){chosen=p;input.value=label(p);close();status.textContent='Selected: '+label(p);onChange(p);}
 function highlight(){[...list.children].forEach((e,i)=>{e.setAttribute('aria-selected',String(i===active));if(i===active){input.setAttribute('aria-activedescendant',e.id);e.scrollIntoView({block:'nearest'});}});}
 async function search(){const ticket=++version,query=input.value.trim();close();if(!query){status.textContent='Type a name or email to find a reviewer.';return;}status.textContent='Searching…';try{const result=await window.robos.searchPeople({query});if(ticket!==version||!host.isConnected)return;items=result.people;list.replaceChildren();items.forEach((p,i)=>{const row=document.createElement('div');row.id='signoff-result-'+i;row.setAttribute('role','option');row.setAttribute('aria-selected','false');const name=document.createElement('strong'),email=document.createElement('span');name.textContent=p.displayName;email.textContent=p.email||p.githubLogin||'';row.append(name,email);row.onmousedown=e=>e.preventDefault();row.onclick=()=>choose(p);list.append(row);});list.hidden=!items.length;input.setAttribute('aria-expanded',String(!!items.length));status.textContent=result.total>20?'Showing 20 of '+result.total+' matches. Keep typing to narrow the results.':items.length?items.length+' matches. Use ↑ ↓ and Enter to choose.':'No matching people. Try another name or email.';}catch(e){if(ticket===version)status.textContent=e.message;}}
 input.oninput=()=>{chosen=null;onChange(null);version++;clearTimeout(timer);close();status.textContent=input.value.trim()?'Searching…':'Type a name or email to find a reviewer.';timer=setTimeout(search,150);};
 input.onkeydown=e=>{if(e.key==='Escape'&&!list.hidden){e.preventDefault();e.stopPropagation();version++;close();return;}if(e.key==='ArrowDown'||e.key==='ArrowUp'){if(!items.length||list.hidden)return;e.preventDefault();active=Math.max(0,Math.min(items.length-1,active+(e.key==='ArrowDown'?1:-1)));highlight();}if(e.key==='Enter'&&!list.hidden){e.preventDefault();if(active>=0)choose(items[active]);}};
 input.onblur=()=>{version++;clearTimeout(timer);close();};
 input.onfocus=()=>{if(!chosen&&input.value.trim())search();};
 if(selected){input.value=label(selected);status.textContent='Selected: '+label(selected);}return {focus:()=>input.focus()};
};
